"use client";
import { useEffect, useMemo, useState } from "react";

const labels: Record<string,string> = { triage:"Triagem", "visual-analyst":"Analista visual", "marketplace-strategist":"Estrategista", copywriter:"Copywriter", "art-director":"Diretor de arte", "virtual-photographer":"Fotógrafo virtual", "compliance-reviewer":"Revisor de conformidade", "quality-director":"Diretor de qualidade" };
const settingLabels: Record<string,string> = { brandName:"Nome da marca", marketplaceTitleLimit:"Limite do título", minimumQualityScore:"Nota mínima", maxProjectBudgetUsd:"Orçamento por anúncio (USD)" };
type Overview = { user:{displayName:string;email:string}; knowledge:any[]; excellence:any[]; settings:any[]; events:any[]; projects:any[]; palettes:any[] };

export default function AdminPage(){
  const [data,setData]=useState<Overview|null>(null); const [error,setError]=useState(""); const [tab,setTab]=useState("agents"); const [selected,setSelected]=useState("triage"); const [content,setContent]=useState<any>(null); const [reason,setReason]=useState(""); const [saving,setSaving]=useState(false); const [paletteCategory,setPaletteCategory]=useState("Mini sabonetes"); const [paletteName,setPaletteName]=useState(""); const [paletteLines,setPaletteLines]=useState(""); const [paletteReason,setPaletteReason]=useState("");
  const load=async()=>{ const response=await fetch("/api/admin/overview",{cache:"no-store"}); const value=await response.json(); if(!response.ok) throw new Error(value.error); setData(value); };
  useEffect(()=>{load().catch((e)=>setError(e.message));},[]);
  const versions=useMemo(()=>data?.knowledge.filter((item)=>item.agent_role===selected)??[],[data,selected]); const published=versions.find((item)=>item.status==="published");
  useEffect(()=>{ if(published) setContent(structuredClone(published.content)); },[selected,published?.id]);
  const saveDraft=async()=>{setSaving(true);setError("");try{const response=await fetch("/api/admin/knowledge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"draft",agentRole:selected,content,changeReason:reason})});const value=await response.json();if(!response.ok)throw new Error(value.error);setReason("");await load();}catch(e){setError(e instanceof Error?e.message:"Falha ao salvar");}finally{setSaving(false)}};
  const publish=async(id:string)=>{if(!confirm("Publicar esta versão para os próximos anúncios?"))return;setSaving(true);try{const response=await fetch("/api/admin/knowledge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"publish",id})});const value=await response.json();if(!response.ok)throw new Error(value.error);await load();}catch(e){setError(e instanceof Error?e.message:"Falha ao publicar");}finally{setSaving(false)}};
  const updateSetting=async(key:string,current:any)=>{const raw=prompt(`Novo valor para ${settingLabels[key]}`,String(current??""));if(raw===null)return;const why=prompt("Motivo obrigatório da alteração");if(!why)return;const value=key==="brandName"?raw:Number(raw);const response=await fetch("/api/admin/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({key,value,changeReason:why})});const result=await response.json();if(!response.ok){setError(result.error);return;}await load();};
  const retire=async(id:string)=>{if(!confirm("Retirar esta referência da Biblioteca de Excelência?"))return;const response=await fetch("/api/admin/excellence",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"retire",id})});const result=await response.json();if(!response.ok){setError(result.error);return;}await load();};
  const savePalette=async()=>{setSaving(true);setError("");try{const options=paletteLines.split("\n").map((line)=>{const [color,...rest]=line.split("|");return{color:color?.trim(),aroma:rest.join("|").trim()}}).filter((item)=>item.color);const response=await fetch("/api/admin/palettes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({category:paletteCategory,name:paletteName,options,changeReason:paletteReason})});const value=await response.json();if(!response.ok)throw new Error(value.error);setPaletteName("");setPaletteLines("");setPaletteReason("");await load();}catch(e){setError(e instanceof Error?e.message:"Falha ao salvar paleta");}finally{setSaving(false)}};
  if(error&&!data)return <main className="admin-denied"><h1>Acesso administrativo</h1><p>{error}</p><a href="/">Voltar ao estúdio</a></main>;
  if(!data)return <main className="admin-loading">Preparando o painel administrativo…</main>;
  const activeSettings=Object.fromEntries(data.settings.filter((s)=>s.status==="active").map((s)=>[s.key,s.value])); const drafts=versions.filter((v)=>v.status==="draft");
  return <main className="admin-shell"><aside><a href="/">← Harmony Studio</a><h1>Centro de<br/>Inteligência</h1><p>Governança dos agentes e padrões de excelência.</p><nav>{[["agents","Agentes"],["palettes","Paletas"],["library","Biblioteca"],["settings","Parâmetros"],["history","Histórico"]].map(([id,name])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{name}</button>)}</nav><small>{data.user.email}</small></aside><section className="admin-main"><header><div><span>PAINEL ADMINISTRATIVO</span><h2>{tab==="agents"?"Especialistas de IA":tab==="palettes"?"Paletas por categoria":tab==="library"?"Biblioteca de Excelência":tab==="settings"?"Parâmetros globais":"Histórico de alterações"}</h2></div><b>Ambiente protegido</b></header>{error&&<div className="admin-error">{error}<button onClick={()=>setError("")}>×</button></div>}
  {tab==="agents"&&<div className="agents-layout"><div className="agent-list">{Object.entries(labels).map(([id,name])=>{const item=data.knowledge.find((v)=>v.agent_role===id&&v.status==="published");return <button className={selected===id?"selected":""} onClick={()=>setSelected(id)} key={id}><i>✦</i><span><b>{name}</b><small>{item?`Versão ${item.version} publicada`:"Sem versão publicada"}</small></span></button>})}</div><div className="agent-editor"><div className="editor-head"><div><small>ESPECIALISTA SELECIONADO</small><h3>{labels[selected]}</h3></div><span>{drafts.length} rascunho(s)</span></div>{content&&<><label>Missão<textarea value={content.mission} onChange={(e)=>setContent({...content,mission:e.target.value})}/></label><div className="editor-grid"><label>Regras obrigatórias<textarea value={content.mandatoryRules.join("\n")} onChange={(e)=>setContent({...content,mandatoryRules:e.target.value.split("\n").filter(Boolean)})}/></label><label>Nunca fazer<textarea value={content.neverDo.join("\n")} onChange={(e)=>setContent({...content,neverDo:e.target.value.split("\n").filter(Boolean)})}/></label><label>Checklist de qualidade<textarea value={content.qualityChecklist.join("\n")} onChange={(e)=>setContent({...content,qualityChecklist:e.target.value.split("\n").filter(Boolean)})}/></label><label>Boas práticas<textarea value={content.bestPractices.join("\n")} onChange={(e)=>setContent({...content,bestPractices:e.target.value.split("\n").filter(Boolean)})}/></label></div><label>Motivo da nova versão<input value={reason} onChange={(e)=>setReason(e.target.value)} placeholder="Ex.: melhorar fidelidade das fotografias"/></label><button className="admin-primary" disabled={saving||!reason.trim()} onClick={saveDraft}>Salvar nova versão como rascunho</button></>}{drafts.length>0&&<div className="drafts"><h4>Rascunhos aguardando publicação</h4>{drafts.map((v)=><article key={v.id}><span>Versão {v.version}</span><p>{v.change_reason}</p><button disabled={saving} onClick={()=>publish(v.id)}>Publicar versão</button></article>)}</div>}</div></div>}
  {tab==="library"&&<div className="admin-cards">{data.excellence.length===0?<div className="admin-empty"><b>Nenhuma referência aprovada ainda</b><p>Os materiais aprovados pelo fluxo poderão ser curados nesta biblioteca.</p></div>:data.excellence.map((item)=><article key={item.id}><small>{item.artifact_type} • {item.marketplace}</small><h3>{item.product_category}</h3><p>{item.approval_reason}</p><div>{item.tags?.map((tag:string)=><span key={tag}>{tag}</span>)}</div><footer><b>{item.status==="active"?"Ativa":"Retirada"}</b>{item.status==="active"&&<button onClick={()=>retire(item.id)}>Retirar</button>}</footer></article>)}</div>}
  {tab==="palettes"&&<div className="palette-admin"><section className="agent-editor"><div className="editor-head"><div><small>NOVA PALETA OU VERSÃO</small><h3>Cores, aromas e variações</h3></div></div><div className="editor-grid"><label>Categoria<select value={paletteCategory} onChange={(e)=>setPaletteCategory(e.target.value)}><option>Mini sabonetes</option><option>Organza</option><option>Caixinha personalizada</option><option>Sagu perfumado</option><option>Outro produto artesanal</option></select></label><label>Nome da paleta<input value={paletteName} onChange={(e)=>setPaletteName(e.target.value)} placeholder="Ex.: Padrão Mini Sabonetes"/></label></div><label>Opções — uma por linha<textarea className="palette-text" value={paletteLines} onChange={(e)=>setPaletteLines(e.target.value)} placeholder={"Rosa BB | Mamãe e Bebê\nAzul BB | Mamãe e Bebê\nLilás | Lavanda"}/></label><label>Motivo da criação ou alteração<input value={paletteReason} onChange={(e)=>setPaletteReason(e.target.value)} placeholder="Ex.: Paleta oficial de produção"/></label><button className="admin-primary" disabled={saving||!paletteName.trim()||!paletteLines.trim()||!paletteReason.trim()} onClick={savePalette}>Salvar e disponibilizar paleta</button></section><div className="admin-cards palette-list">{data.palettes.filter((item)=>item.status==="active").map((item)=><article key={item.id}><small>{item.category} • versão {item.version}</small><h3>{item.name}</h3><p>{item.options.length} opções salvas</p><div>{item.options.slice(0,5).map((option:any)=><span key={option.color}>{option.color}{option.aroma?` • ${option.aroma}`:""}</span>)}</div></article>)}</div></div>}
  {tab==="settings"&&<div className="settings-grid">{Object.keys(settingLabels).map((key)=><article key={key}><small>PARÂMETRO GLOBAL</small><h3>{settingLabels[key]}</h3><strong>{String(activeSettings[key]??"Padrão do sistema")}</strong><button onClick={()=>updateSetting(key,activeSettings[key])}>Criar nova versão</button></article>)}</div>}
  {tab==="history"&&<div className="audit-list">{data.events.map((event)=><article key={event.id}><i>✓</i><div><b>{event.event_type}</b><span>{event.entity_type} • {event.entity_id}</span></div><time>{new Date(event.created_at).toLocaleString("pt-BR")}</time></article>)}</div>}</section></main>;
}
