import { getChatGPTUser } from "../../../chatgpt-auth.ts";
import { assertWorkflowOwner, bindings } from "../shared.ts";
export const runtime = "edge";
const shotTypes = ["catalog-cover", "product-detail", "variations", "use-occasion", "versatile-composition"];

export async function GET(request: Request) {
  try { const user = await getChatGPTUser(); if (!user) return Response.json({ error: "Faça login para continuar" }, { status: 401 }); const url = new URL(request.url); const category = url.searchParams.get("category")?.trim() ?? ""; const modelName = url.searchParams.get("modelName")?.trim() ?? ""; if (!category) return Response.json({ references: [] }); const { db } = bindings(); const result = await db.prepare(`SELECT id, title, scope, category, model_name, shot_type, transfer_mode, guidance, never_do_json
    FROM studio_visual_references WHERE status = 'active' AND ((scope = 'model' AND category = ? AND lower(model_name) = lower(?)) OR (scope = 'category' AND category = ?) OR scope = 'global')
    ORDER BY shot_type, CASE scope WHEN 'model' THEN 1 WHEN 'category' THEN 2 ELSE 3 END, created_at DESC LIMIT 60`).bind(category, modelName, category).all<any>(); return Response.json({ references: (result.results ?? []).map((row) => ({ id: row.id, title: row.title, scope: row.scope, category: row.category, modelName: row.model_name, shotType: row.shot_type, transferMode: row.transfer_mode, guidance: row.guidance, neverDo: JSON.parse(row.never_do_json), imageUrl: `/api/studio/visual-directions/asset?id=${encodeURIComponent(row.id)}` })) });
  } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Falha ao buscar direção visual" }, { status: 500 }); }
}

export async function POST(request: Request) {
  try { const user = await getChatGPTUser(); if (!user) return Response.json({ error: "Faça login para continuar" }, { status: 401 }); const { workflowId, selections } = await request.json() as { workflowId?: string; selections?: Record<string,string|null> }; if (!workflowId || !selections) return Response.json({ error: "Seleção visual inválida" }, { status: 400 }); const { db } = bindings(); await assertWorkflowOwner(db, workflowId, user.id); const clean: Record<string,string|null> = {}; for (const shot of shotTypes) { if (!(shot in selections)) continue; const value = selections[shot]; if (value === null) { clean[`visual-production-${shotTypes.indexOf(shot) + 1}`] = null; continue; } if (typeof value !== "string") continue; const row = await db.prepare("SELECT id FROM studio_visual_references WHERE id = ? AND shot_type = ? AND status = 'active'").bind(value, shot).first(); if (!row) return Response.json({ error: "Uma referência escolhida não está mais disponível" }, { status: 409 }); clean[`visual-production-${shotTypes.indexOf(shot) + 1}`] = value; }
    const run = await db.prepare("SELECT configuration_json FROM studio_workflow_runs WHERE id = ?").bind(workflowId).first<{ configuration_json: string }>(); if (!run) return Response.json({ error: "Trabalho não encontrado" }, { status: 404 }); const configuration = JSON.parse(run.configuration_json); configuration.initialData = { ...(configuration.initialData ?? {}), visualReferenceSelections: clean }; const now = new Date().toISOString(); await db.batch([db.prepare("UPDATE studio_workflow_runs SET configuration_json = ?, updated_at = ? WHERE id = ?").bind(JSON.stringify(configuration), now, workflowId), db.prepare("INSERT INTO studio_audit_events (id, project_id, actor_id, event_type, entity_type, entity_id, before_json, after_json, metadata_json, created_at) SELECT ?, project_id, ?, 'visual_selection.confirmed', 'workflow_run', id, NULL, ?, NULL, ? FROM studio_workflow_runs WHERE id = ?").bind(crypto.randomUUID(), user.id, JSON.stringify(clean), now, workflowId)]); return Response.json({ selections: clean });
  } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Falha ao confirmar direção visual" }, { status: 500 }); }
}
