import type { OrchestrationRepository } from "../../application/ports/orchestration-repository.ts";
import type { AgentRole } from "../../domain/intelligence/agent-knowledge.ts";
import type { StageKey, StageRun, StageStatus } from "../../domain/orchestration/workflow-plan.ts";
import type { WorkflowRun, WorkflowRunStatus } from "../../domain/workflows/workflow-run.ts";
import type { D1DatabasePort } from "./d1-types.ts";

type WorkflowRow = { id: string; project_id: string; status: WorkflowRunStatus; configuration_json: string; started_at: string | null; completed_at: string | null; created_at: string; updated_at: string };
type StageRow = { id: string; workflow_run_id: string; stage_key: StageKey; attempt: number; status: StageStatus; idempotency_key: string; agent_role: AgentRole; knowledge_version_id: string | null; input_hash: string | null; output_json: string | null; error_json: string | null; usage_json: string | null; started_at: string | null; completed_at: string | null; created_at: string; updated_at: string };
const workflow = (row: WorkflowRow): WorkflowRun => ({ id: row.id, projectId: row.project_id, status: row.status, configuration: JSON.parse(row.configuration_json), startedAt: row.started_at, completedAt: row.completed_at, createdAt: row.created_at, updatedAt: row.updated_at });
const stage = (row: StageRow): StageRun => ({ id: row.id, workflowRunId: row.workflow_run_id, stageKey: row.stage_key, attempt: row.attempt, status: row.status, idempotencyKey: row.idempotency_key, agentRole: row.agent_role, knowledgeVersionId: row.knowledge_version_id, inputHash: row.input_hash, output: row.output_json ? JSON.parse(row.output_json) : null, error: row.error_json ? JSON.parse(row.error_json) : null, usage: row.usage_json ? JSON.parse(row.usage_json) : null, startedAt: row.started_at, completedAt: row.completed_at, createdAt: row.created_at, updatedAt: row.updated_at });

export class D1OrchestrationRepository implements OrchestrationRepository {
  private readonly db: D1DatabasePort;
  constructor(db: D1DatabasePort) { this.db = db; }
  async saveWorkflow(run: WorkflowRun) { await this.db.prepare(`INSERT INTO studio_workflow_runs (id, project_id, status, configuration_json, started_at, completed_at, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET status=excluded.status, configuration_json=excluded.configuration_json, started_at=excluded.started_at, completed_at=excluded.completed_at, updated_at=excluded.updated_at`).bind(run.id, run.projectId, run.status, JSON.stringify(run.configuration), run.startedAt, run.completedAt, run.createdAt, run.updatedAt).run(); }
  async findWorkflow(id: string) { const row = await this.db.prepare("SELECT * FROM studio_workflow_runs WHERE id = ?").bind(id).first<WorkflowRow>(); return row ? workflow(row) : null; }
  async saveStages(stages: StageRun[]) { if (!stages.length) return; const statements = stages.map((item) => this.db.prepare(`INSERT INTO studio_stage_runs (id, workflow_run_id, stage_key, attempt, status, idempotency_key, agent_role, knowledge_version_id, input_hash, output_json, error_json, usage_json, started_at, completed_at, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET status=excluded.status, knowledge_version_id=excluded.knowledge_version_id, input_hash=excluded.input_hash, output_json=excluded.output_json, error_json=excluded.error_json, usage_json=excluded.usage_json, started_at=excluded.started_at, completed_at=excluded.completed_at, updated_at=excluded.updated_at`).bind(item.id, item.workflowRunId, item.stageKey, item.attempt, item.status, item.idempotencyKey, item.agentRole, item.knowledgeVersionId, item.inputHash, item.output ? JSON.stringify(item.output) : null, item.error ? JSON.stringify(item.error) : null, item.usage ? JSON.stringify(item.usage) : null, item.startedAt, item.completedAt, item.createdAt, item.updatedAt)); await this.db.batch(statements); }
  async listStages(workflowRunId: string) { const result = await this.db.prepare("SELECT * FROM studio_stage_runs WHERE workflow_run_id = ? ORDER BY created_at ASC, attempt ASC").bind(workflowRunId).all<StageRow>(); return (result.results || []).map(stage); }
}
