"use client";
import { useEffect, useState } from "react";
import { optimizeImageUpload, VISUAL_REFERENCE_MAX_BYTES } from "../../image-upload";

const SHOTS = [["catalog-cover","1. Capa principal"],["product-detail","2. Detalhe e acabamento"],["variations","3. Cores e variações"],["purchase-contents","4. Conteúdo da compra"],["use-occasion","5. Ocasião de uso"],["product-size","6. Tamanho e medidas"]] as const;
const CATEGORIES = ["Mini sabonetes","Organza","Caixinha personalizada","Sagu perfumado","Outro produto artesanal"];
const initialReference = { title:"", shotType:SHOTS[0][0], guidance:"", neverDo:"Não copiar o formato do produto da referência\nNão adicionar textos não previstos\nNão alterar o produto real" };

export default function VisualStandardsPage() {
  const [category,setCategory]=useState(CATEGORIES[0]); const [data,setData]=useState<any>(null); const [message,setMessage]=useState(""); const [busy,setBusy]=useState("");
  const [reference,setReference]=useState(initialReference); const [image,setImage]=useState<File|null>(null); const [moves,setMoves]=useState<Record<string,{category:string;shotType:string}>>({});
  const load=async()=>{const response=await fetch("/api/admin/overview",{cache:"no-store"});const value=await response.json();if(!response.ok)throw new Error(value.error);setData(value);};
  useEffect(()=>{load().catch((error)=>setMessage(error.message));},[]);
  const call=async(url:string,body:any)=>{const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw new Error(value.error);return value;};
  const consolidate=async(shotType:string)=>{setBusy(shotType);try{const value=await call("/api/admin/visual-standards",{action:"consolidate",category,shotType,reason:"Manual consolidado a partir de referências analisadas e aprovadas"});setMessage(`Manual v${value.version} criado como rascunho.`);await load();}catch(error){setMessage(error instanceof Error?error.message:"Falha ao consolidar");}finally{setBusy("");}};
  const publish=async(standard:any)=>{if(!confirm("Publicar este manual para o Fotógrafo Virtual?"))return;setBusy(standard.shot_type);try{await call("/api/admin/visual-standards",{action:"publish",id:standard.id,category,shotType:standard.shot_type});setMessage("Manual publicado e conectado ao agente.");await load();}catch(error){setMessage(error instanceof Error?error.message:"Falha ao publicar");}finally{setBusy("");}};
  const upload=async()=>{if(!image||!reference.title.trim()||!reference.guidance.trim())return;setBusy("upload");setMessage("Otimizando e analisando a referência…");try{const optimized=await optimizeImageUpload(image,{maxBytes:VISUAL_REFERENCE_MAX_BYTES,maxDimension:1800});const form=new FormData();Object.entries({...reference,scope:"category",category,modelName:"",transferMode:"style-composition"}).forEach(([key,value])=>form.append(key,value));form.append("image",optimized);const response=await fetch("/api/admin/visual-references",{method:"POST",body:form});const value=await response.json();if(!response.ok)throw new Error(value.error);const approved=confirm(`Análise automática:\n\nComposição: ${value.analysis.composition}\nIluminação: ${value.analysis.lighting}\nFundo: ${value.analysis.background}\nPaleta: ${value.analysis.palette}\n\nAprovar para o aprendizado?`);await call("/api/admin/visual-references",{action:approved?"approve-analysis":"reject-analysis",id:value.id});setReference(initialReference);setImage(null);setMessage(approved?"Referência aprovada para o aprendizado.":"Referência mantida fora do aprendizado.");await load();}catch(error){setMessage(error instanceof Error?error.message:"Falha ao cadastrar referência");}finally{setBusy("");}};
  const manage=async(item:any,action:"move"|"retire")=>{if(action==="retire"&&!confirm("Retirar esta referência do aprendizado? O histórico será preservado e manuais derivados serão invalidados."))return;const target=moves[item.id]??{category:item.category,shotType:item.shot_type};setBusy(item.id);try{await call("/api/admin/visual-references",{action,id:item.id,...target});setMessage(action==="move"?"Referência movida e conectada ao destino. Manuais derivados foram invalidados; consolide e publique o manual correto.":"Referência retirada. Manuais derivados foram invalidados para não usar conhecimento antigo.");await load();}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível alterar a referência");}finally{setBusy("");}};
  if(!data)return <main className="admin-loading">Carregando governança visual…</main>;
  return <main className="admin-shell">
    <aside><a href="/admin">← Centro de Inteligência</a><h1>Manuais<br/>Visuais</h1><p>O agente recebe apenas o manual publicado da categoria e da função atual.</p></aside>
    <section className="admin-main">
      <header><div><span>GOVERNANÇA VISUAL</span><h2>Seis funções do anúncio</h2></div><b>Revisão humana obrigatória</b></header>
      <label>Categoria<select value={category} onChange={(event)=>setCategory(event.target.value)}>{CATEGORIES.map((item)=><option key={item}>{item}</option>)}</select></label>
      {message&&<div className="admin-error">{message}</div>}
      <section className="agent-editor"><div className="editor-head"><div><small>NOVA REFERÊNCIA</small><h3>Ensinar e revisar um padrão</h3></div></div><div className="editor-grid"><label>Função da imagem<select value={reference.shotType} onChange={(event)=>setReference({...reference,shotType:event.target.value})}>{SHOTS.map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>Nome da referência<input value={reference.title} onChange={(event)=>setReference({...reference,title:event.target.value})}/></label></div><label>Imagem aprovada<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event)=>setImage(event.target.files?.[0]??null)}/></label><label>O que deve ser transferido<textarea value={reference.guidance} onChange={(event)=>setReference({...reference,guidance:event.target.value})}/></label><label>O que nunca copiar<textarea value={reference.neverDo} onChange={(event)=>setReference({...reference,neverDo:event.target.value})}/></label><button className="admin-primary" disabled={busy==="upload"||!image||!reference.title.trim()||!reference.guidance.trim()} onClick={upload}>{busy==="upload"?"Analisando…":"Analisar referência"}</button></section>
      <div className="admin-cards">{SHOTS.map(([id,label])=>{const references=data.visualReferences.filter((item:any)=>item.category===category&&item.shot_type===id&&item.status==="active"&&item.analysis_status==="approved");const versions=data.visualStandards.filter((item:any)=>item.category===category&&item.shot_type===id);const published=versions.find((item:any)=>item.status==="published");const draft=versions.find((item:any)=>item.status==="draft");return <article key={id}><small>{label}</small><h3>{published?`Manual v${published.version} conectado`:"Sem manual publicado"}</h3><p>{references.length} referência(s) aprovada(s). Mínimo: 3.</p>
        {references.length>0&&<details><summary>Ver e administrar referências</summary>{references.map((item:any)=>{const target=moves[item.id]??{category:item.category,shotType:item.shot_type};return <div className="visual-reference-manager" key={item.id}><img src={item.imageUrl} alt={item.title}/><b>{item.title}</b><label>Mover para categoria<select value={target.category} onChange={(event)=>setMoves({...moves,[item.id]:{...target,category:event.target.value}})}>{CATEGORIES.map((name)=><option key={name}>{name}</option>)}</select></label><label>Função<select value={target.shotType} onChange={(event)=>setMoves({...moves,[item.id]:{...target,shotType:event.target.value}})}>{SHOTS.map(([shot,label])=><option value={shot} key={shot}>{label}</option>)}</select></label><button disabled={busy===item.id} onClick={()=>manage(item,"move")}>Mover referência</button><button disabled={busy===item.id} onClick={()=>manage(item,"retire")}>Retirar</button></div>;})}</details>}
        {published&&<div><span>✓ O Fotógrafo Virtual usa este manual</span></div>}{draft&&<details><summary>Revisar rascunho v{draft.version}</summary><pre>{JSON.stringify(draft.specification,null,2)}</pre><button onClick={()=>publish(draft)}>Aprovar e publicar</button></details>}<footer><button disabled={busy===id||references.length<3} onClick={()=>consolidate(id)}>{busy===id?"Consolidando…":"Consolidar novo manual"}</button></footer></article>;})}</div>
    </section>
  </main>;
}
