"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { dbRequest, getStoredSession, HarmonySession, isSupabaseConfigured, productImageUrl, Profile, signIn, signOut } from "./lib/supabase-rest";

type View = "home" | "new" | "requests" | "products" | "team" | "profile";
type Product = { id:string; name:string; color?:string; description?:string; unit:string; physical_stock:number; reserved_stock:number; minimum_stock:number; image_path?:string; active:boolean };
type RequestRow = { id:string; protocol:number; status:string; notes?:string; scheduled_for?:string; created_at:string; requested_by:string };
const labels:Record<string,string>={pending:"Pendente",separating:"Em separação",scheduled:"Agendada",delivered:"Entregue",cancelled:"Cancelada"};

export default function Home(){
  const [session,setSession]=useState<HarmonySession|null>(null),[profile,setProfile]=useState<Profile|null>(null),[view,setView]=useState<View>("home");
  const [products,setProducts]=useState<Product[]>([]),[requests,setRequests]=useState<RequestRow[]>([]),[team,setTeam]=useState<Profile[]>([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState("");
  useEffect(()=>{if(!isSupabaseConfigured){setLoading(false);return}getStoredSession().then(async s=>{if(s)try{await loadAccount(s)}catch{await signOut(s)}setLoading(false)})},[]);
  async function loadAccount(s:HarmonySession){const rows=await dbRequest<Profile[]>(s,`profiles?id=eq.${s.user.id}&select=*`);if(!rows[0]||rows[0].status!=="active")throw new Error("Cadastro inativo ou não localizado.");setSession(s);setProfile(rows[0]);await loadData(s,rows[0])}
  async function loadData(s=session,p=profile){if(!s||!p)return;const [a,b]=await Promise.all([dbRequest<Product[]>(s,"products?select=*&order=name.asc"),dbRequest<RequestRow[]>(s,"requests?select=*&order=created_at.desc")]);setProducts(a);setRequests(b);if(p.role==="admin")setTeam(await dbRequest<Profile[]>(s,"profiles?select=*&order=full_name.asc"))}
  async function login(user:string,password:string){await loadAccount(await signIn(user,password))}
  async function logout(){await signOut(session);setSession(null);setProfile(null);setView("home")}
  function flash(s:string){setNotice(s);setTimeout(()=>setNotice(""),3000)}
  if(loading)return <div className="loading"><img src="/harmony-store-logo.jpg" alt="Harmony Store"/><span/></div>;
  if(!session||!profile)return <Login onLogin={login}/>;
  const admin=profile.role==="admin";
  return <main className="shell"><aside className="sidebar"><button className="brand" onClick={()=>setView("home")}><img src="/harmony-store-logo.jpg" alt="Harmony Store Oficial"/><span><b>Harmony Store</b><small>Gestão de produção</small></span></button><div className="account"><i>{initials(profile.full_name)}</i><span><b>{profile.full_name}</b><small>{admin?"Administradora":"Colaboradora"}</small></span></div><nav><small>PRINCIPAL</small><Nav icon="⌂" label="Visão geral" active={view==="home"} onClick={()=>setView("home")}/>{!admin&&<Nav icon="＋" label="Nova solicitação" active={view==="new"} onClick={()=>setView("new")}/>}<Nav icon="▤" label={admin?"Solicitações":"Meus pedidos"} active={view==="requests"} onClick={()=>setView("requests")}/>{admin&&<><small>GESTÃO</small><Nav icon="◇" label="Produtos e estoque" active={view==="products"} onClick={()=>setView("products")}/><Nav icon="♙" label="Colaboradoras" active={view==="team"} onClick={()=>setView("team")}/></>}<small>CONTA</small><Nav icon="○" label="Meu perfil" active={view==="profile"} onClick={()=>setView("profile")}/></nav><button className="logout" onClick={logout}>Sair do sistema</button></aside><section className="content"><header className="topbar"><b>✦ Ambiente oficial Harmony</b><span>Dados protegidos e sincronizados</span></header>{view==="home"&&<Dashboard profile={profile} products={products} requests={requests} goNew={()=>setView("new")}/>} {view==="new"&&<NewRequest session={session} profile={profile} products={products} done={async()=>{await loadData();setView("requests");flash("Solicitação enviada com sucesso.")}}/>}{view==="requests"&&<Requests rows={requests} admin={admin}/>} {view==="products"&&<Products rows={products}/>} {view==="team"&&<Team rows={team}/>} {view==="profile"&&<ProfilePage profile={profile} logout={logout}/>}</section>{notice&&<div className="toast">✓ {notice}</div>}</main>
}

function Login({onLogin}:{onLogin:(a:string,b:string)=>Promise<void>}){const [user,setUser]=useState(""),[pass,setPass]=useState(""),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await onLogin(user,pass)}catch(x){const m=x instanceof Error?x.message:"Não foi possível entrar.";setError(/invalid login/i.test(m)?"Login ou senha incorretos.":m)}finally{setBusy(false)}}return <main className="login-page"><section className="login-story"><p className="eyebrow">HARMONY STORE OFICIAL</p><h1>Cuidado artesanal,<br/><em>gestão impecável.</em></h1><p>Materiais, solicitações e entregas reunidos em um ambiente seguro, criado para a rotina da nossa produção.</p><div className="artisan"><i>✦</i><span><b>Feito para a nossa essência</b><small>Organização leve, delicada e eficiente.</small></span></div></section><section className="login-panel"><div className="login-box"><img src="/harmony-store-logo.jpg" alt="Harmony Store Oficial"/><p className="eyebrow">ACESSO RESTRITO</p><h2>Bem-vinda</h2><p>Use o login criado pela administradora.</p>{!isSupabaseConfigured&&<div className="warning"><b>Preparação da versão oficial</b><span>O Supabase precisa ser conectado para liberar os acessos.</span></div>}<form onSubmit={submit}><label>Login<input value={user} onChange={e=>setUser(e.target.value)} placeholder="seu.login" autoComplete="username" required/></label><label>Senha<div className="password"><input type={show?"text":"password"} value={pass} onChange={e=>setPass(e.target.value)} autoComplete="current-password" required/><button type="button" onClick={()=>setShow(!show)}>{show?"Ocultar":"Ver"}</button></div></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy||!isSupabaseConfigured}>{busy?"Entrando…":"Entrar no sistema"}</button></form><small className="safe">Seus dados são protegidos. Nunca compartilhe sua senha.</small></div></section></main>}

function Dashboard({profile,products,requests,goNew}:{profile:Profile;products:Product[];requests:RequestRow[];goNew:()=>void}){const admin=profile.role==="admin",low=products.filter(p=>+p.physical_stock-+p.reserved_stock<=+p.minimum_stock).length;return <Page eyebrow="VISÃO GERAL" title={`Olá, ${profile.full_name.split(" ")[0]}.`} subtitle={admin?"Aqui está o resumo da operação da Harmony Store.":"Acompanhe seus pedidos e solicite materiais para a produção."} action={!admin?<button className="primary" onClick={goNew}>＋ Nova solicitação</button>:undefined}><div className="metrics"><Metric value={requests.filter(r=>!["delivered","cancelled"].includes(r.status)).length} label="Em andamento"/><Metric value={requests.filter(r=>r.status==="pending").length} label="Aguardando separação"/><Metric value={requests.filter(r=>r.status==="delivered").length} label="Entregas concluídas"/>{admin&&<Metric value={low} label="Estoque baixo"/>}</div><section className="card"><div className="card-head"><h2>Solicitações recentes</h2><p>Movimentações mais atuais</p></div><RequestList rows={requests.slice(0,6)}/></section></Page>}

function NewRequest({session,profile,products,done}:{session:HarmonySession;profile:Profile;products:Product[];done:()=>Promise<void>}){const [qty,setQty]=useState<Record<string,number>>({}),[notes,setNotes]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const selected=useMemo(()=>products.filter(p=>(qty[p.id]||0)>0),[products,qty]);async function send(){setBusy(true);setError("");try{const r=await dbRequest<RequestRow[]>(session,"requests",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({requested_by:profile.id,notes,status:"pending"})});await dbRequest(session,"request_items",{method:"POST",body:JSON.stringify(selected.map(p=>({request_id:r[0].id,product_id:p.id,requested_quantity:qty[p.id]})))});await done()}catch(x){setError(x instanceof Error?x.message:"Não foi possível enviar.")}finally{setBusy(false)}}return <Page eyebrow="SOLICITAÇÃO" title="Escolha seus materiais" subtitle="A empresa definirá a data e se será entrega ou coleta."><div className="catalog-layout"><section className="catalog">{products.filter(p=>p.active).map(p=><article className="product" key={p.id}>{p.image_path?<img src={productImageUrl(p.image_path)} alt={p.name}/>:<i style={{background:p.color||"#f5c5dc"}}>✦</i>}<div><small>{p.unit}</small><h3>{p.name}</h3><p>{p.description||p.color||"Material de produção"}</p><b>{+p.physical_stock-+p.reserved_stock} disponíveis</b></div><div className="quantity"><button onClick={()=>setQty(q=>({...q,[p.id]:Math.max(0,(q[p.id]||0)-1)}))}>−</button><input type="number" min="0" step="0.001" value={qty[p.id]||0} onChange={e=>setQty(q=>({...q,[p.id]:Math.max(0,+e.target.value)}))}/><button onClick={()=>setQty(q=>({...q,[p.id]:(q[p.id]||0)+1}))}>＋</button></div></article>)}</section><aside className="summary"><p className="eyebrow">SEU PEDIDO</p><h2>{selected.length} produtos</h2>{selected.map(p=><div key={p.id}><span>{p.name}</span><b>{qty[p.id]} {p.unit}</b></div>)}{!selected.length&&<p className="empty">Escolha ao menos um material.</p>}<label>Observação<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Finalidade, lote ou detalhe importante…"/></label>{error&&<div className="error">{error}</div>}<button className="primary full" disabled={!selected.length||busy} onClick={send}>{busy?"Enviando…":"Enviar solicitação"}</button></aside></div></Page>}

function Requests({rows,admin}:{rows:RequestRow[];admin:boolean}){return <Page eyebrow="OPERAÇÃO" title={admin?"Solicitações":"Meus pedidos"} subtitle={admin?"Analise, ajuste e prepare os pedidos recebidos.":"Somente as suas solicitações aparecem aqui."}><section className="card"><RequestList rows={rows}/></section></Page>}
function Products({rows}:{rows:Product[]}){return <Page eyebrow="GESTÃO" title="Produtos e estoque" subtitle="Cadastro e disponibilidade das matérias-primas." action={<button className="primary" disabled>＋ Cadastrar produto</button>}><div className="table"><header><span>Produto</span><span>Estoque físico</span><span>Reservado</span><span>Disponível</span><span>Situação</span></header>{rows.map(p=>{const a=+p.physical_stock-+p.reserved_stock;return <article key={p.id}><span className="product-name">{p.image_path?<img src={productImageUrl(p.image_path)} alt=""/>:<i style={{background:p.color||"#f3c5da"}}/>}<b>{p.name}<small>{p.unit}</small></b></span><span>{p.physical_stock}</span><span>{p.reserved_stock}</span><b>{a}</b><Status value={a<=+p.minimum_stock?"low":"active"}/></article>})}</div><p className="phase">A edição completa de produtos será conectada na próxima etapa da implantação oficial.</p></Page>}
function Team({rows}:{rows:Profile[]}){return <Page eyebrow="CADASTROS" title="Equipe Harmony" subtitle="Colaboradoras e administradoras cadastradas."><div className="team">{rows.map(p=><article key={p.id}><i>{initials(p.full_name)}</i><div><h3>{p.full_name}</h3><p>{p.department||(p.role==="admin"?"Administração":"Produção")}</p><small>{p.username} · {p.harmony_id}</small></div><Status value={p.status}/></article>)}</div><p className="phase">A criação e edição segura de acessos será habilitada com a chave administrativa protegida.</p></Page>}
function ProfilePage({profile,logout}:{profile:Profile;logout:()=>void}){return <Page eyebrow="MINHA CONTA" title="Meu perfil" subtitle="Informações vinculadas ao seu acesso."><section className="profile"><header><i>{initials(profile.full_name)}</i><div><h2>{profile.full_name}</h2><p>{profile.role==="admin"?"Administradora":"Colaboradora"}</p></div></header><dl><div><dt>Login</dt><dd>{profile.username}</dd></div><div><dt>Harmony ID</dt><dd>{profile.harmony_id}</dd></div><div><dt>Setor</dt><dd>{profile.department||"Não informado"}</dd></div><div><dt>Situação</dt><dd>{profile.status==="active"?"Ativo":"Inativo"}</dd></div></dl><button className="outline" onClick={logout}>Sair do aplicativo</button></section></Page>}

function Page({eyebrow,title,subtitle,action,children}:{eyebrow:string;title:string;subtitle:string;action?:React.ReactNode;children:React.ReactNode}){return <div className="page"><header className="page-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><span>{subtitle}</span></div>{action}</header>{children}</div>}
function Nav({icon,label,active,onClick}:{icon:string;label:string;active:boolean;onClick:()=>void}){return <button className={active?"active":""} onClick={onClick}><i>{icon}</i>{label}</button>}
function Metric({value,label}:{value:number;label:string}){return <article><span>✦</span><b>{value}</b><p>{label}</p></article>}
function RequestList({rows}:{rows:RequestRow[]}){if(!rows.length)return <div className="empty-state">Nenhuma solicitação encontrada.</div>;return <div className="requests">{rows.map(r=><article key={r.id}><div><small>SOLICITAÇÃO</small><b>#{String(r.protocol).padStart(4,"0")}</b></div><div><strong>{r.notes||"Materiais para produção"}</strong><small>{new Date(r.created_at).toLocaleDateString("pt-BR")}</small></div><div><small>DATA PROGRAMADA</small><b>{r.scheduled_for?new Date(r.scheduled_for).toLocaleDateString("pt-BR"):"A definir"}</b></div><span className={r.status}>{labels[r.status]||r.status}</span></article>)}</div>}
function Status({value}:{value:string}){return <span className={`status ${value}`}>{value==="active"?"Ativo":value==="inactive"?"Inativo":"Estoque baixo"}</span>}
function initials(name:string){return name.split(" ").filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()}
