"use client";

import { ChangeEvent, useMemo, useState } from "react";

type Doc = { id:number; name:string; kind:string; supplier:string; idNumber:string; date:string; due:string; value:number; category:string; payment:string; status:"Processado"|"Revisar"|"Vinculado"; confidence:number };

const initialDocs: Doc[] = [
  {id:1,name:"NF 1842 · Papelaria Criativa",kind:"Nota fiscal",supplier:"Papelaria Criativa",idNumber:"42.519.308/0001-17",date:"21 jul 2026",due:"28 jul 2026",value:1248.9,category:"Materiais e insumos",payment:"Boleto",status:"Processado",confidence:98},
  {id:2,name:"Comprovante PIX · Studio Lima",kind:"Comprovante",supplier:"Studio Lima",idNumber:"***.804.219-**",date:"20 jul 2026",due:"Pago em 20 jul",value:690,category:"Serviços",payment:"Pix",status:"Vinculado",confidence:100},
  {id:3,name:"Boleto · Energia Sul",kind:"Conta a pagar",supplier:"Energia Sul",idNumber:"08.914.017/0001-88",date:"18 jul 2026",due:"23 jul 2026",value:438.72,category:"Despesas fixas",payment:"Boleto",status:"Revisar",confidence:82},
];

const money = new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const nav = ["Início","Documentos","Contas a pagar","Movimentações","Relatórios"];

export default function Page(){
  const [docs,setDocs]=useState(initialDocs); const [active,setActive]=useState("Início"); const [query,setQuery]=useState(""); const [upload,setUpload]=useState(false); const [processing,setProcessing]=useState(false); const [review,setReview]=useState<Doc|null>(null); const [toast,setToast]=useState("");
  const say=(v:string)=>{setToast(v);setTimeout(()=>setToast(""),2600)};
  const filtered=useMemo(()=>docs.filter(d=>Object.values(d).join(" ").toLowerCase().includes(query.toLowerCase())),[docs,query]);
  const onFile=(e:ChangeEvent<HTMLInputElement>)=>{if(!e.target.files?.[0])return;setProcessing(true);setTimeout(()=>{const d:Doc={id:Date.now(),name:`Cupom · Mercado do Centro`,kind:"Cupom fiscal",supplier:"Mercado do Centro",idNumber:"17.204.883/0001-04",date:"Hoje, 14:32",due:"Pago hoje",value:286.4,category:"Materiais e insumos",payment:"Pix",status:"Revisar",confidence:91};setDocs(x=>[d,...x]);setProcessing(false);setUpload(false);setReview(d)},1800)};
  const confirm=()=>{if(!review)return;setDocs(x=>x.map(d=>d.id===review.id?{...d,status:"Processado",confidence:100}:d));setReview(null);say("Documento confirmado e lançado automaticamente")};
  const total=docs.reduce((a,d)=>a+d.value,0); const due=docs.filter(d=>d.kind==="Conta a pagar").reduce((a,d)=>a+d.value,0);
  return <div className="shell">
    <aside className="sidebar"><div className="brand"><img src="/harmony-logo-oficial.jpg" alt="Harmony Store"/><div><b>Harmony Store</b><small>assistente financeiro</small></div></div><nav>{nav.map((n,i)=><button key={n} onClick={()=>setActive(n)} className={active===n?"active":""}><i>{["⌂","▱","◷","↕","◫"][i]}</i>{n}{n==="Contas a pagar"&&<em>3</em>}</button>)}</nav><div className="ai-card"><span>✦</span><b>IA ativa</b><p>Todos os documentos são analisados automaticamente.</p><small><i/> Funcionando normalmente</small></div><div className="profile"><span>MC</span><div><b>Marina Costa</b><small>Harmony Store</small></div><button>•••</button></div></aside>
    <main><header className="top"><button className="mobile-brand">H</button><label className="search"><span>⌕</span><input aria-label="Pesquisar" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar fornecedor, valor, CPF ou CNPJ..."/><kbd>⌘ K</kbd></label><div className="top-actions"><button className="icon">?</button><button className="icon">♢<i/></button><button className="user">MC</button></div></header>
      <div className="content"><section className="welcome"><div><p>VISÃO GERAL</p><h1>Olá, Marina <span>👋</span></h1><h2>Seu financeiro, quase no piloto automático.</h2></div><button className="send" onClick={()=>setUpload(true)}><span>＋</span><div><b>Enviar documento</b><small>Foto, PDF, boleto ou comprovante</small></div></button></section>
        <section className="ai-banner"><span>✦</span><div><b>A IA organizou 12 documentos esta semana</b><p>9 foram lançados automaticamente e apenas 3 precisam da sua confirmação.</p></div><button onClick={()=>{setActive("Documentos");setQuery("Revisar")}}>Revisar pendências <b>3</b> →</button></section>
        <section className="stats"><article><header><span>Movimentado no mês</span><i>↗</i></header><b>{money.format(total+18475)}</b><p><strong>↑ 8,4%</strong> comparado a junho</p></article><article><header><span>Contas a pagar</span><i>◷</i></header><b>{money.format(due+7961.28)}</b><p><em>3 vencem nos próximos 7 dias</em></p></article><article><header><span>Economia de tempo</span><i>✦</i></header><b>6h 40min</b><p>estimadas pela automação este mês</p></article></section>
        <section className="grid"><article className="panel"><header><div><h3>Documentos recentes</h3><p>A IA extrai, classifica e relaciona para você.</p></div><button onClick={()=>{setActive("Documentos");setQuery("")}}>Ver todos →</button></header><div className="doc-head"><span>DOCUMENTO</span><span>VALOR</span><span>STATUS</span><span/></div>{filtered.slice(0,4).map(d=><div className="doc" key={d.id}><div className="doc-name"><i>{d.kind==="Comprovante"?"✓":d.kind==="Conta a pagar"?"▤":"▱"}</i><div><b>{d.name}</b><span>{d.category} · {d.payment}</span></div></div><strong>{money.format(d.value)}</strong><span className={`status ${d.status.toLowerCase()}`}>{d.status==="Processado"?"✓ ":d.status==="Vinculado"?"↗ ":"! "}{d.status}</span><button onClick={()=>d.status==="Revisar"?setReview(d):say("Detalhes do documento abertos")}>•••</button></div>)}</article>
          <article className="panel upcoming"><header><div><h3>Próximos vencimentos</h3><p>Contas que merecem atenção.</p></div><button onClick={()=>setActive("Contas a pagar")}>Ver contas →</button></header>{[["23","JUL","Energia Sul","Despesas fixas","438,72","Amanhã"],["25","JUL","Aluguel do estúdio","Estrutura","2.800,00","Em 3 dias"],["28","JUL","Papelaria Criativa","Materiais","1.248,90","Em 6 dias"]].map(x=><div className="bill" key={x[2]}><div className="date"><b>{x[0]}</b><span>{x[1]}</span></div><div><b>{x[2]}</b><span>{x[3]}</span></div><div><strong>R$ {x[4]}</strong><span>{x[5]}</span></div></div>)}</article></section>
        <section className="bottom"><article className="categories panel"><header><div><h3>Gastos por categoria</h3><p>Julho de 2026</p></div><button>•••</button></header>{[["Materiais e insumos",42,"R$ 8.420"],["Serviços",27,"R$ 5.385"],["Despesas fixas",19,"R$ 3.810"],["Outros",12,"R$ 2.440"]].map((x,i)=><div className="bar" key={x[0]}><span>{x[0]}</span><div><i style={{width:`${x[1]}%`}} className={`c${i}`}/></div><b>{x[2]}</b><em>{x[1]}%</em></div>)}</article><article className="assistant"><span>✦</span><small>ASSISTENTE IA</small><h3>Pergunte sobre seu financeiro</h3><p>“Quanto gastei com fornecedores este mês?”</p><button onClick={()=>say("Assistente pronto para conversar")}>Conversar com a IA →</button></article></section>
      </div>
    </main>
    {upload&&<div className="overlay" onMouseDown={()=>setUpload(false)}><section className="upload-modal" onMouseDown={e=>e.stopPropagation()}><button className="x" onClick={()=>setUpload(false)}>×</button><span className="upload-icon">✦</span><small>CAPTURA INTELIGENTE</small><h2>Envie. A IA faz o resto.</h2><p>Reconhecemos nota fiscal, cupom, boleto, Pix e comprovante.</p><label className="drop"><input type="file" accept="image/*,.pdf" onChange={onFile}/>{processing?<><i className="spinner"/><b>Analisando documento...</b><span>Extraindo dados e buscando relações</span></>:<><i>＋</i><b>Arraste ou selecione um arquivo</b><span>PDF, JPG ou PNG · até 20 MB</span></>}</label><div className="steps"><span>1 <b>Enviar</b></span><i>→</i><span>2 <b>IA analisa</b></span><i>→</i><span>3 <b>Você confirma se precisar</b></span></div></section></div>}
    {review&&<div className="overlay"><section className="review"><header><div><span>✦</span><div><small>REVISÃO RÁPIDA</small><h2>Confirme só o que importa</h2></div></div><button onClick={()=>setReview(null)}>×</button></header><div className="confidence"><span>IA encontrou os dados</span><b>{review.confidence}% de confiança</b></div><div className="fields"><label>Fornecedor<input value={review.supplier} onChange={e=>setReview({...review,supplier:e.target.value})}/></label><label>CNPJ<input value={review.idNumber} onChange={e=>setReview({...review,idNumber:e.target.value})}/></label><label>Valor<input value={money.format(review.value)} readOnly/></label><label>Data<input value={review.date} readOnly/></label><label>Categoria sugerida<select value={review.category} onChange={e=>setReview({...review,category:e.target.value})}><option>Materiais e insumos</option><option>Serviços</option><option>Despesas fixas</option></select></label><label>Pagamento<input value={review.payment} readOnly/></label></div><div className="match">✓ Nenhuma cobrança pendente correspondente foi encontrada.</div><footer><button onClick={()=>setReview(null)}>Corrigir depois</button><button onClick={confirm}>Confirmar e lançar →</button></footer></section></div>}
    {toast&&<div className="toast">✓ {toast}</div>}
  </div>;
}
