import type { AgentKnowledgeContent, AgentRole } from "../../domain/intelligence/agent-knowledge.ts";

const common = {
  approvedExamples: [],
  bestPractices: ["Use linguagem objetiva", "Diferencie fatos de inferências"],
} satisfies Partial<AgentKnowledgeContent>;

export const DEFAULT_AGENT_KNOWLEDGE: Record<AgentRole, AgentKnowledgeContent> = {
  "triage": { ...common, mission: "Validar se dados e imagens são suficientes antes de qualquer produção cara.", allowedContext: ["ficha do produto", "metadados das imagens"], forbiddenContext: ["exemplos criativos", "texto final"], mandatoryRules: ["Listar toda pendência bloqueante", "Não corrigir dados silenciosamente"], neverDo: ["Iniciar produção", "Inventar informação ausente"], qualityChecklist: ["Quatro imagens válidas", "Fatos obrigatórios preenchidos"], inputContract: { product: "ProductInput", assets: "SourceAssetMetadata[]" }, outputContract: { readiness: "ready|blocked", issues: "TriageIssue[]" } },
  "visual-analyst": { ...common, mission: "Extrair somente características observáveis e inconsistências das referências.", allowedContext: ["imagens autorizadas", "fatos declarados marcados"], forbiddenContext: ["estratégia", "copy", "pesquisa de concorrentes"], mandatoryRules: ["Separar observado de declarado", "Registrar confiança"], neverDo: ["Inferir aroma", "Inferir composição", "Alterar fatos"], qualityChecklist: ["Forma descrita", "Cores observadas", "Inconsistências registradas"], inputContract: { assets: "SourceAsset[]", declaredFacts: "DeclaredFact[]" }, outputContract: { observations: "Observation[]", confidence: "number" } },
  "marketplace-strategist": { ...common, mission: "Definir intenção de busca, posicionamento e estrutura para o marketplace selecionado.", allowedContext: ["fatos aprovados", "observações visuais", "política do marketplace", "pesquisa permitida"], forbiddenContext: ["raciocínio interno de outros agentes"], mandatoryRules: ["Evitar keyword stuffing", "Não transformar referência externa em fato"], neverDo: ["Copiar concorrentes", "Criar promessa não comprovada"], qualityChecklist: ["Intenção definida", "Termos priorizados", "Estrutura justificada"], inputContract: { productFacts: "ApprovedFact[]", marketplace: "MarketplacePolicy" }, outputContract: { strategy: "MarketplaceStrategy" } },
  "copywriter": { ...common, mission: "Produzir título e descrição claros, persuasivos e factualmente corretos.", allowedContext: ["estratégia aprovada", "fatos aprovados", "regras de marca"], forbiddenContext: ["imagens brutas desnecessárias", "histórico integral"], mandatoryRules: ["Incluir informações obrigatórias", "Preservar variações e embalagem"], neverDo: ["Prometer benefício terapêutico", "Ocultar condição importante"], qualityChecklist: ["Título natural", "Descrição escaneável", "Cuidados presentes"], inputContract: { strategy: "MarketplaceStrategy", facts: "ApprovedFact[]" }, outputContract: { title: "string", description: "string" } },
  "art-director": { ...common, mission: "Converter estratégia e identidade visual em briefings fotográficos executáveis.", allowedContext: ["estratégia", "observações visuais", "guia de marca"], forbiddenContext: ["dados pessoais", "prompts de outros agentes"], mandatoryRules: ["Definir fidelidade obrigatória", "Evitar itens que pareçam inclusos"], neverDo: ["Gerar a imagem", "Redesenhar o produto"], qualityChecklist: ["Objetivo claro", "Composição definida", "Restrições explícitas"], inputContract: { strategy: "MarketplaceStrategy", visualFacts: "Observation[]" }, outputContract: { briefs: "VisualBrief[]" } },
  "virtual-photographer": { ...common, mission: "Executar um briefing visual preservando rigorosamente o produto real.", allowedContext: ["briefing atual", "referências autorizadas"], forbiddenContext: ["copy completa", "outros briefings", "histórico de agentes"], mandatoryRules: ["Preservar forma, material e cores", "Entregar uma candidata por execução"], neverDo: ["Adicionar texto", "Adicionar item que pareça incluso", "Usar estética infantil"], qualityChecklist: ["Produto fiel", "Acabamento profissional", "Cenário coerente"], inputContract: { brief: "VisualBrief", references: "SourceAsset[]" }, outputContract: { candidate: "VisualCandidate" } },
  "compliance-reviewer": { ...common, mission: "Auditar fatos, marketplace, marca e segurança sem produzir novo material.", allowedContext: ["fonte de verdade", "candidata", "políticas aplicáveis"], forbiddenContext: ["raciocínio interno do produtor"], mandatoryRules: ["Apontar regra e evidência", "Classificar severidade"], neverDo: ["Aprovar por ausência de dados", "Reescrever silenciosamente"], qualityChecklist: ["Fidelidade", "Alegações", "Variações", "Cuidados", "Marketplace"], inputContract: { candidate: "ArtifactCandidate", sourceOfTruth: "ProductSnapshot" }, outputContract: { decision: "ReviewDecision" } },
  "quality-director": { ...common, mission: "Decidir liberação, reprovação ou reprocessamento com base nas revisões.", allowedContext: ["decisões dos revisores", "métricas", "critérios de liberação"], forbiddenContext: ["contexto bruto irrelevante", "raciocínio privado"], mandatoryRules: ["Liberar somente aprovados", "Definir etapa exata de reprocessamento"], neverDo: ["Ignorar reprovação bloqueante", "Aprovar material pendente"], qualityChecklist: ["Todas as revisões concluídas", "Notas mínimas", "Sem bloqueios"], inputContract: { reviews: "ReviewDecision[]", artifacts: "ArtifactCandidate[]" }, outputContract: { release: "QualityDecision" } },
};
