import { requireStudioAdmin, adminDb, adminError, audit } from "../shared.ts";
import { getStudioBindings } from "../../../../src/harmony-studio/infrastructure/runtime/studio-bindings.ts";
import { R2AssetStorage, type R2BucketPort } from "../../../../src/harmony-studio/infrastructure/storage/r2-asset-storage.ts";

const scopes = ["global", "category", "model"];
const shots = ["catalog-cover", "product-detail", "variations", "purchase-contents", "use-occasion", "product-size"];
const transfers = ["style", "style-composition", "scenario", "lighting"];
export const runtime = "edge";

function base64(buffer: ArrayBuffer) { const bytes = new Uint8Array(buffer); let value = ""; for (let index = 0; index < bytes.length; index += 0x8000) value += String.fromCharCode(...bytes.subarray(index, index + 0x8000)); return btoa(value); }
async function analyzeReference(image: File, guidance: string, neverDo: string[]) {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error("OPENAI_API_KEY não configurada");
  const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: "gpt-5.6-sol", instructions: "Analise esta referência de direção de arte. Extraia somente propriedades visuais transferíveis; nunca trate o formato ou identidade do produto fotografado como padrão. Responda no JSON Schema solicitado.", input: [{ role: "user", content: [{ type: "input_text", text: JSON.stringify({ guidance, neverDo }) }, { type: "input_image", detail: "high", image_url: `data:${image.type};base64,${base64(await image.arrayBuffer())}` }] }], text: { format: { type: "json_schema", name: "visual_reference_analysis", strict: true, schema: { type: "object", additionalProperties: false, required: ["composition","lighting","background","palette","typography","transferableTraits","risks"], properties: { composition: { type: "string" }, lighting: { type: "string" }, background: { type: "string" }, palette: { type: "string" }, typography: { type: "string" }, transferableTraits: { type: "array", items: { type: "string" } }, risks: { type: "array", items: { type: "string" } } } } } }, store: false }) });
  if (!response.ok) throw new Error(`A análise visual automática falhou (${response.status})`);
  const payload = await response.json() as any; const text = payload.output_text ?? payload.output?.flatMap((item: any) => item.content ?? []).find((item: any) => item.type === "output_text")?.text;
  if (!text) throw new Error("A análise visual não retornou dados");
  return JSON.parse(text);
}

export async function POST(request: Request) {
  try {
    const user = await requireStudioAdmin(); const db = adminDb(); const contentType = request.headers.get("content-type") ?? "";
    if (contentType.includes("application/json")) { const body = await request.json() as any; if (!body.id) throw new Error("Ação inválida"); const now = new Date().toISOString(); if (body.action === "retire") { await db.batch([db.prepare("UPDATE studio_visual_references SET status = 'retired', retired_at = ? WHERE id = ? AND status = 'active'").bind(now, body.id), db.prepare("UPDATE studio_visual_standard_versions SET status = 'archived', archived_at = ? WHERE status IN ('draft','published') AND instr(source_reference_ids_json, ?) > 0").bind(now, body.id)]); } else if (body.action === "approve-analysis") await db.prepare("UPDATE studio_visual_references SET analysis_status = 'approved', approved_at = ? WHERE id = ? AND status = 'active'").bind(now, body.id).run(); else if (body.action === "reject-analysis") await db.prepare("UPDATE studio_visual_references SET analysis_status = 'rejected', approved_at = NULL WHERE id = ? AND status = 'active'").bind(body.id).run(); else if (body.action === "move") { const category = String(body.category ?? "").trim(); const shotType = String(body.shotType ?? ""); if (!category || !shots.includes(shotType)) throw new Error("Destino inválido"); await db.batch([db.prepare("UPDATE studio_visual_references SET scope = 'category', category = ?, model_name = NULL, shot_type = ? WHERE id = ? AND status = 'active'").bind(category, shotType, body.id), db.prepare("UPDATE studio_visual_standard_versions SET status = 'archived', archived_at = ? WHERE status IN ('draft','published') AND instr(source_reference_ids_json, ?) > 0").bind(now, body.id)]); } else throw new Error("Ação inválida"); await audit({ actorId: user.id, eventType: `visual_reference.${body.action}`, entityType: "visual_reference", entityId: body.id, after: body.action === "move" ? { category: body.category, shotType: body.shotType, derivedManualsInvalidated: true } : { derivedManualsInvalidated: body.action === "retire" } }); return Response.json({ ok: true }); }
    const form = await request.formData(); const image = form.get("image"); const title = String(form.get("title") ?? "").trim(); const scope = String(form.get("scope") ?? ""); const category = String(form.get("category") ?? "").trim(); const modelName = String(form.get("modelName") ?? "").trim(); const shotType = String(form.get("shotType") ?? ""); const transferMode = String(form.get("transferMode") ?? ""); const guidance = String(form.get("guidance") ?? "").trim(); const neverDo = String(form.get("neverDo") ?? "").split("\n").map((item) => item.trim()).filter(Boolean);
    if (!(image instanceof File) || !["image/jpeg", "image/png", "image/webp"].includes(image.type) || image.size > 800_000) throw new Error("Envie uma imagem JPG, PNG ou WebP otimizada pelo aplicativo");
    if (!title || !guidance || !scopes.includes(scope) || !shots.includes(shotType) || !transfers.includes(transferMode)) throw new Error("Preencha todos os campos obrigatórios");
    if (scope !== "global" && !category) throw new Error("Escolha a categoria desta referência"); if (scope === "model" && !modelName) throw new Error("Informe o modelo relacionado");
    const analysis = await analyzeReference(image, guidance, neverDo);
    const id = crypto.randomUUID(); const key = `visual-learning/${id}/${image.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`; const storage = new R2AssetStorage(getStudioBindings().STUDIO_ASSETS as R2BucketPort); const stored = await storage.put(key, await image.arrayBuffer(), image.type, { kind: "visual-reference", createdBy: user.id }); const now = new Date().toISOString();
    try { await db.prepare("INSERT INTO studio_visual_references (id, title, scope, category, model_name, shot_type, transfer_mode, guidance, never_do_json, storage_key, content_type, size_bytes, sha256, status, analysis_json, analysis_status, created_by, created_at, retired_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'active', ?, 'pending', ?, ?, NULL)").bind(id, title, scope, scope === "global" ? null : category, scope === "model" ? modelName : null, shotType, transferMode, guidance, JSON.stringify(neverDo), stored.key, stored.contentType, stored.sizeBytes, stored.sha256, JSON.stringify(analysis), user.id, now).run(); } catch (error) { await storage.delete(key); throw error; }
    await audit({ actorId: user.id, eventType: "visual_reference.created_pending_approval", entityType: "visual_reference", entityId: id, after: { title, scope, category, modelName, shotType, transferMode, analysis } }); return Response.json({ id, analysis, analysisStatus: "pending" });
  } catch (error) { return adminError(error); }
}
