(()=>{
const HELP_TOPICS=[
  {id:'shipping-planning',roles:['admin','collaborator','receiver'],icon:'🚚',title:'Planejamento de envios',summary:'Organizar os próximos envios do e-commerce em cartões, produtos, kits compostos e microtarefas.',steps:['O módulo aparece somente para a gerente de e-commerce designada pelo ADM principal. O ADM principal mantém acesso de contingência e auditoria.','Crie um plano com plataforma, conta, data, horário e observações. Marque FULL quando o envio for nessa modalidade.','Use Produto do catálogo para reutilizar nome e foto oficiais; use Item exclusivo para um produto interno deste módulo; e use Kit composto para reunir dois ou mais modelos e cores.','O Kit composto fica salvo para próximos envios. Ele pode ter foto própria; sem foto, o sistema usa a imagem do primeiro componente. Cada componente continua exibindo sua foto oficial.','Ao excluir um kit salvo, ele deixa de aparecer em novos planos, mas os planos antigos e seus componentes permanecem preservados no histórico.','No campo Cor, escolha uma cor oficial ou Nova combinação de cores. Uma combinação reúne de 2 a 4 cores oficiais e fica somente neste módulo.','Em Anúncio, escolha a quantidade por volume. Depois informe quantos kits ou caixas serão preparados; o total é calculado automaticamente.','Em um plano FULL, use Solicitar caixas do Inventário para selecionar caixas físicas exatas do mesmo modelo e cor. A reserva retira a caixa da disponibilidade, mas não baixa seu saldo.','A baixa definitiva acontece somente após um ADM ou colaborador de Recebimento confirmar a transferência física da caixa completa para o e-commerce. Cancelar a reserva devolve a caixa à disponibilidade.','Marque cada produto depois de concluí-lo. A linha fica verde e a barra do cartão mostra o progresso real.','O envio só pode ficar Pronto para coleta e ser arquivado quando todos os produtos estiverem concluídos.','Use Gerar PDF dentro do plano para imprimir somente a lista aberta, em formato A4, no computador, tablet ou celular.','Planos cancelados e finalizados permanecem no Histórico com usuário, data e alterações auditadas.']},
  {id:'agenda-harmony',roles:['admin'],icon:'🗓️',title:'Agenda Harmony',summary:'Organizar tarefas, datas e compromissos administrativos sem duplicar solicitações.',steps:['A Central de Pendências continua sendo o único painel da Home que lista solicitações abertas.','O calendário semanal da Agenda mostra tarefas próprias, compromissos e boletos; dias vazios aparecem como Sem compromissos.','Toque em uma data para abrir a Agenda completa já filtrada naquele dia. No celular, selecione o dia e use Abrir agenda deste dia.','Use Nova tarefa para compromissos administrativos e defina início, prazo, prioridade, lembrete e lista de verificação.','Ordens de produção continuam disponíveis na Agenda completa e podem ser concluídas somente no acompanhamento, sem alterar produção, recebimento, estoque ou pagamento.','A faixa Inteligência do dia mostra até três informações úteis. A IA não repete a lista da Central de Pendências e nunca altera dados operacionais.','A Home das colaboradoras e do perfil Recebimento não foi modificada.','Lembretes no celular dependem das notificações ativadas no perfil e só são enviados somente para ADMs.']},
  {id:'start',roles:['collaborator','receiver','admin'],icon:'🌷',title:'Primeiros passos',summary:'Entrar, navegar, atualizar dados e sair com segurança.',steps:['Use o menu inferior no celular ou lateral no computador.','Toque em Atualizar quando precisar buscar dados recentes.','Em Meu perfil você altera foto e senha e pode sair da conta.']},
  {id:'request',roles:['collaborator','receiver'],icon:'📝',title:'Solicitar matéria-prima',summary:'Monte uma solicitação e acompanhe somente os seus pedidos.',steps:['Abra Nova solicitação e informe a quantidade de cada material.','A lista mostra somente matérias-primas de produção; café, limpeza e outros suprimentos ficam no módulo interno.','Revise a lista e envie; a empresa definirá data e entrega ou coleta.','Enquanto estiver pendente, abra o pedido para editar ou cancelar.']},
  {id:'notifications',roles:['collaborator','receiver','admin'],icon:'🔔',title:'Notificações',summary:'Leia avisos internos e acompanhe comunicados importantes da Harmony.',steps:['O número no menu mostra quantas notificações ainda não foram lidas.','Toque no aviso para abrir os detalhes e confirmar a leitura.','O ADM principal envia avisos individuais pelo cadastro ou globais para toda a equipe.']},
  {id:'admin-requests',roles:['admin'],icon:'📋',title:'Administrar solicitações',summary:'Separar, ajustar, agendar, concluir ou cancelar pedidos.',steps:['Abra a solicitação e confira todos os itens.','Marque Separado para destacar o item em verde. Use Sem estoque somente depois da contagem física: o saldo será zerado, a ocorrência ficará vermelha e a reposição será aberta automaticamente.','O botão Finalizar separação só é liberado quando nenhum item estiver esquecido.','Agende todos os itens para o mesmo dia e finalize informando quem entregou e recebeu.','O ADM principal pode usar Editar solicitação completa para adicionar produtos ou corrigir quantidades em qualquer fase; entregas concluídas ajustam estoque e relatórios automaticamente.']},
  {id:'products',roles:['admin'],icon:'🧼',title:'Produtos e estoque',summary:'Cadastrar materiais, fotos, fornecedores e estoque com segurança.',steps:['Cadastre nome, unidade, categoria, cor, foto e limites de estoque.','Para etiquetas e materiais com nome, escolha Estoque individual por colaboradora e use Gerenciar estoques. Cada mulher terá saldo próprio.','Defina se a reposição do produto deve gerar uma compra de fornecedor ou uma produção interna.','Use Conferência de estoque para acompanhar divergências, reposições e exportar relatórios.','Use campos personalizados quando um material precisar de informação própria.','As alterações de produto, estoque e fornecedor são salvas juntas.']},
  {id:'production',roles:['collaborator','receiver','admin'],icon:'📦',title:'Produção recebida',summary:'Conferência por caixa, modelo, cor e quantidade oficial.',steps:['Recebimento ou ADM registra vários itens dentro de uma única coleta.','Se outra caixa da mesma coleta aparecer depois, use Reabrir e editar para acrescentá-la ao registro original.','Coletas com pagamento já realizado ficam protegidas; as demais são recalculadas e registradas no histórico.']},
  {id:'production-orders',roles:['collaborator','receiver','admin'],icon:'📋',title:'Ordens de produção',summary:'Planejamento semanal por colaboradora, com fotos, cores e quantidades.',steps:['O ADM cria a ordem usando os mesmos modelos e cores do catálogo de produtos acabados.','A colaboradora recebe uma notificação, abre a lista e confirma que recebeu as orientações.','Se a confirmação chegar por WhatsApp, telefone ou pessoalmente, o ADM pode registrar a confirmação externa com data, meio e auditoria.','Use Gerar PDF para imprimir ou salvar a lista profissionalmente.','Este módulo não calcula pagamento; os valores continuam exclusivamente no recebimento pela contagem oficial.']},
  {id:'production-inventory',roles:['receiver','admin'],icon:'🧼',title:'Inventário de Produção',summary:'Controlar o saldo de mini sabonetes acabados com origem por colaboradora, caixa, etiqueta e data.',steps:['Use Registrar nova caixa e toque em Gerar código. O identificador CX-000001 continua a sequência atual, é permanente e nunca reutilizado.','Selecione modelo, cor e colaboradora e escolha Gerar etiqueta 150 × 100. O pré-cadastro ainda não soma unidades ao estoque.','Use Gerar PDF 150 × 100 para baixar uma única página paisagem já configurada no tamanho térmico. Abra o PDF baixado para imprimir; não imprima o PNG diretamente dentro do Gmail, pois ele adiciona margens e cabeçalhos.','Baixe o PNG somente quando o aplicativo da impressora pedir uma imagem. A etiqueta usa a foto do modelo em alto contraste e o QR Code abre a caixa apenas após login autorizado.','Cole a etiqueta na caixa física e use Confirmar etiqueta aplicada. Apenas essa confirmação libera a quantidade no saldo e no contador.','Se fechar o aplicativo, retome a identificação pelo quadro Etiquetas pendentes. Um cancelamento preserva o código no histórico.','Para uma caixa antiga ou com etiqueta danificada, abra Saldo atual, entre nos detalhes do modelo e use Gerar / reimprimir etiqueta na caixa. Informe o motivo; o mesmo código e QR Code serão mantidos.','A aba Caixas em estoque usa a foto original do modelo e organiza as caixas da mais nova para a mais antiga.','Toque no botão rosa Transferir caixa: o sistema utiliza todo o saldo e registra o destino Estoque do e-commerce.','Ajustes exigem contagem física e motivo e devem ser feitos antes da transferência. Nenhum histórico é apagado.','Relatórios e etiquetas não exibem valores e não alteram pagamentos ou matérias-primas.']},
  {id:'payments',roles:['collaborator','admin'],icon:'💗',title:'Pagamentos semanais',summary:'Acompanhar fechamentos de segunda a domingo.',steps:['O ADM fecha a semana somente depois da conferência.','A colaboradora visualiza o valor após o fechamento, em Meus pagamentos.','Correções exigem reabertura administrativa e ficam registradas.']},
  {id:'intelligence',roles:['admin'],icon:'📈',title:'Central de Inteligência',summary:'Transformar dados reais em estatísticas, gráficos, prioridades e decisões conferíveis.',steps:['A navegação possui cinco áreas principais: Painel inteligente, Shopee Analytics, Operação, Compras e parceiros e Ideias e evolução.','O antigo Inventário com IA agora faz parte do Painel inteligente, sem ocupar uma aba adicional.','O Painel inteligente reúne estatísticas e gráficos reais do Inventário; a IA interpreta os dados consolidados sem fazer contas livres.','Shopee Analytics recebe três planilhas independentes: Estatísticas da Loja, Funil de Produtos e Promoções e Descontos.','Em Operação, use o seletor interno para abrir consumo, matérias-primas, e-commerce, colaboradoras, planejado × recebido e qualidade dos dados.','Em Compras e parceiros ficam pedidos, fornecedores e planejamento de reposição.','Use Ver evidências antes de tomar qualquer decisão sugerida pela IA.','A IA não altera estoque, ordens, pagamentos ou cadastros; as ações continuam exigindo confirmação humana.','Abrir a tela não gera custo. Somente uma nova análise usa a API, respeitando o orçamento mensal definido pelo ADM principal.']},
  {id:'shopee-intelligence',roles:['admin'],icon:'🛍️',title:'Shopee Analytics',summary:'Importar relatórios oficiais e acompanhar vendas, funil, marketing, promoções e insights com IA.',steps:['Abra Inteligência e escolha Shopee Analytics.','Em Importações, a primeira seção é exclusiva para adicionar dados de uma nova data ou período. Escolha Estatísticas da Loja, Funil de Produtos ou Promoções e Descontos.','Use Selecionar nova planilha para um dia ou uma semana ainda não registrada. Dias repetidos são reconhecidos e preservados sem nova soma.','Os cartões de Últimos períodos recebidos são somente informativos; eles não alteram nem substituem arquivos.','Para corrigir um arquivo errado, encontre o período no Histórico auditável e use Corrigir período. O sistema exige uma planilha com exatamente o mesmo período selecionado.','O resultado informa quantos dias foram adicionados ou ignorados e o painel abre automaticamente o período reconhecido. Não existe espera depois da mensagem de sucesso.','Na Visão geral, alterne o gráfico entre Faturamento (R$) e Pedidos. Toque ou passe o mouse em um dia para conferir realizado e pago.','A central executiva também reúne funil, origem do tráfego, movimento dos produtos, qualidade dos dados e leitura da IA sem duplicar cálculos.','Produtos mostra o funil completo da visita ao pagamento e o desempenho dos anúncios. Marketing separa as fontes de tráfego. Promoções compara campanhas e formatos.','Os gráficos e cálculos são produzidos pelo banco e não usam créditos da API.','Analisar agora com IA envia apenas os dados consolidados, gera recomendações com evidências e respeita o orçamento mensal.','A IA não altera planilhas, produtos, estoque, pedidos, pagamentos ou campanhas da Shopee.']},
  {id:'internal-supplies',roles:['admin','receiver'],icon:'🧺',title:'Suprimentos e compras internas',summary:'Solicitar itens do e-commerce e registrar compras por cupom fiscal.',steps:['Recebimento marca somente os itens que estão faltando; não precisa informar quantidade ou valor.','Este catálogo é separado das matérias-primas de produção.','O ADM pode cadastrar uma foto em cada suprimento para facilitar a identificação.','O ADM abre a solicitação, fotografa o cupom e acompanha as etapas de envio, leitura e conferência antes de revisar os dados.','Se a leitura falhar, a imagem permanece selecionada para tentar novamente ou trocar o arquivo.','Se um item comprado continuar pendente por ter outro nome no cupom, o ADM usa Vincular item do cupom, escolhe a linha correta e registra o motivo.','Compras não solicitadas entram como Compra direta, sem criar uma solicitação fictícia.','O relatório compara preço anterior e atual, diferença em reais e percentual, média, menor e maior preço.']},
  {id:'bills',roles:['admin'],icon:'▣',title:'Boletos',summary:'Cadastrar, conferir e acompanhar contas a pagar com segurança.',steps:['Fotografe o boleto ou escolha uma imagem ou PDF salvo no aparelho.','Acompanhe as etapas de envio, leitura e conferência; o percentual da interpretação é estimado e só chega a 100% após a resposta.','Se ocorrer uma falha, o documento permanece selecionado para nova tentativa.','Confira beneficiário, valor, vencimento e linha digitável antes de cadastrar.','A leitura inteligente nunca paga o boleto e a confirmação no banco continua sendo manual.']},
  {id:'ideas',roles:['admin'],icon:'💡',title:'Ideias e Evolução',summary:'Registrar melhorias e preparar uma solicitação organizada para o Codex.',steps:['Registre título, área, prioridade, descrição e o problema que deseja resolver.','Use a imagem opcional somente quando ela ajudar a demonstrar a ideia.','Toque em Preparar para o Codex para copiar um texto com contexto, impacto, segurança, riscos e pedido de plano antes da implementação.']},
  {id:'team',roles:['admin'],icon:'👥',title:'Pessoas e acessos',summary:'Cadastrar, editar, desativar e proteger contas.',steps:['Crie login e senha temporária forte para cada pessoa.','A pessoa troca a senha no primeiro acesso.','Cadastros com histórico são desativados, nunca apagados junto com seus registros.']},
  {id:'security',roles:['collaborator','receiver','admin'],icon:'🔐',title:'Segurança da conta',summary:'Boas práticas simples para proteger o acesso.',steps:['Nunca compartilhe sua senha ou códigos de acesso.','Use Sair do sistema quando o aparelho for compartilhado.','Se notar algo diferente, avise o ADM e troque a senha.']},
  {id:'health',roles:['admin'],icon:'🩺',title:'Saúde do Sistema',summary:'Interpretar disponibilidade, backup, Storage e alertas.',steps:['Verde significa operação normal; amarelo pede acompanhamento; vermelho exige ação.','O painel mostra dados resumidos, nunca senhas ou informações pessoais.','Backup só fica verde depois de uma cópia válida e recente.']},
];
const QUICK={
  'shipping-planning':['Crie um cartão para cada envio futuro e informe plataforma, conta e prazo.','Use Produto do catálogo, Item exclusivo ou Kit composto conforme a necessidade.','Kits compostos são reutilizáveis, aceitam foto própria e preservam os planos antigos mesmo quando retirados da lista.','Crie combinações reutilizáveis com 2, 3 ou 4 cores; elas ficam somente no Planejamento de envios.','Anúncio × kits ou caixas gera o total de unidades sem conta manual.','Em planos FULL, reserve caixas exatas do Inventário; a baixa ocorre somente após confirmação física por ADM ou Recebimento.','Marque cada linha concluída; somente um plano 100% conferido pode ficar pronto para coleta.','Itens exclusivos pertencem apenas ao módulo e não alteram o catálogo principal.','O PDF contém somente o plano aberto e funciona em A4 no computador, tablet e celular.'],
  'agenda-harmony':['A Central de Pendências lista solicitações; o calendário da Home mostra somente tarefas planejadas, compromissos e boletos.','Dias sem atividade permanecem visíveis para facilitar o planejamento da semana.','Toque em uma data para abrir a Agenda completa já filtrada.','A Inteligência do dia destaca no máximo três informações e não repete a lista de solicitações.','A IA só organiza e recomenda; abrir a Agenda não gera custo e nenhuma ação operacional é automática.','Use o lembrete somente depois de ativar as notificações no seu perfil.'],
  home:['Veja o resumo do dia e as solicitações mais recentes.','Os cartões mudam conforme o seu perfil e mostram somente dados permitidos.','ADMs acessam compra direta com IA e boleto com IA em um toque; Recebimento mantém somente o atalho permitido do Inventário de Produção.'],
  new:['Informe qualquer quantidade necessária e revise antes de enviar.','A data e a forma de entrega ou coleta serão definidas pela empresa.'],
  requests:['Abra um cartão para consultar detalhes e ações disponíveis.','Colaboradoras veem apenas os próprios pedidos; ADM vê a operação completa.','Na separação administrativa, confira cada item como Separado ou Sem estoque; a finalização fica bloqueada enquanto existir item pendente.','O botão Editar solicitação completa aparece somente para o ADM principal e registra o motivo de cada correção.'],
  notifications:['O contador mostra os avisos ainda não abertos.','Toque em uma notificação para confirmar a leitura e consultar o prazo.','Somente o ADM principal pode enviar avisos individuais ou globais.'],
  products:['Cadastros, estoque e fornecedor são salvos em uma única operação segura.','Use Estoque individual por colaboradora somente em produtos personalizados; cada solicitante verá exclusivamente o próprio saldo.','No botão Gerenciar estoques, o ADM informa o físico e o mínimo de cada mulher. O reservado é movimentado automaticamente.','Defina Compra de fornecedor ou Produção interna para orientar a reposição automática quando o estoque físico for confirmado como zerado.','Use Conferência de estoque para analisar ocorrências e concluir reposições.','Use uma foto leve para facilitar a identificação no celular.','Marque Ocultar para colaboradoras de produção nos produtos exclusivos do e-commerce; ADMs e recebimento continuarão vendo o item.'],
  production:['ADM principal, ADM e Recebimento podem editar coletas abertas de toda a equipe.','Em uma semana fechada, use Reabrir e editar; a data e a colaboradora permanecem protegidas.','Depois de salvar, a contagem oficial e o total semanal são recalculados automaticamente.'],
  categories:['Categorias organizam o catálogo e podem ser desativadas sem apagar produtos.'],
  team:['Somente ADM administra acessos.','Cadastros com histórico são desativados para preservar solicitações e pagamentos.'],
  fields:['Crie somente os campos realmente necessários.','Campos inativos deixam de aparecer nos novos cadastros.'],
  audit:['Use filtros para localizar alterações por pessoa, ação ou período.','O histórico é imutável e gerado por operações confiáveis.'],
  production:['Registre vários modelos e cores dentro da mesma coleta.','Pagamento usa sempre a quantidade oficial conferida.'],
  'production-orders':['O ADM monta uma lista individual com modelo, cor, foto e quantidade.','Rascunhos ficam visíveis somente para os ADMs; ao enviar, a colaboradora recebe uma notificação.','A ordem é planejamento e nunca altera a contagem oficial ou o pagamento.'],
  'production-inventory':['Registre cada caixa separadamente e use Gerar código antes de salvar. A sequência já existente é mantida.','O código CX da caixa é permanente: nunca é duplicado, alterado ou reutilizado.','Gere a etiqueta paisagem 150 × 100 em PNG, PDF ou impressão térmica e confirme somente depois de colá-la na caixa.','Para imprimir sem escala manual, abra o PDF baixado. O PNG é destinado aos aplicativos de impressoras que importam imagens.','Enquanto a etiqueta estiver pendente, a quantidade não entra no saldo. Retome pelo quadro amarelo no topo.','Em uma caixa disponível, use Gerar / reimprimir etiqueta quando a via estiver danificada ou quando a caixa for anterior ao sistema de etiquetas. O motivo, o usuário e o horário ficam registrados sem alterar estoque.','O QR Code é protegido: exige login e perfil ADM ou Recebimento para consultar a caixa.','Novos modelos, cores e colaboradoras aparecem automaticamente a partir dos cadastros oficiais.','O contador do topo inclui somente caixas disponíveis e atualiza imediatamente após confirmação ou transferência.','Em Caixas em estoque, localize a caixa pela placa, foto original, cor, quantidade, colaboradora e data.','Use o botão rosa Transferir caixa. A quantidade não é digitada porque a saída é sempre integral.','Confira e ajuste o saldo antes da transferência; depois dela, a quantidade fica protegida.','Este módulo é interno e não altera pagamentos, recebimentos ou estoque de matérias-primas.'],
  intelligence:['Use Painel inteligente para ver estatísticas, gráficos do Inventário e prioridades automáticas no mesmo lugar.','Shopee Analytics mantém os relatórios do marketplace em uma área separada e auditável.','Abra Operação para consultar os relatórios detalhados sem misturá-los com a visão executiva.','Compras e parceiros reúne pedidos, fornecedores e planejamento de reposição.','Confira sempre as evidências da IA antes de agir.','A IA recomenda, mas nunca altera estoque, produção ou pagamentos sozinha.'],
  'internal-supplies':['Recebimento solicita apenas os itens que estão faltando, sem quantidade.','O catálogo interno não se mistura com a solicitação de matéria-prima.','No Catálogo, o ADM pode cadastrar, trocar ou remover a foto do suprimento.','O ADM pode anexar um cupom à solicitação ou registrar uma compra direta.','Se a descrição do mercado for diferente, use Vincular item do cupom e confirme a linha correta com uma justificativa.','A barra mostra envio, leitura e conferência; se houver falha, a imagem continua selecionada.','Confira todos os dados extraídos da foto antes de confirmar; o relatório registra o histórico de preços.'],
  bills:['Fotografe o boleto ou escolha uma imagem ou PDF já salvo.','A barra de progresso acompanha as etapas da leitura inteligente.','Confira todos os dados antes de cadastrar ou pagar.'],
  health:['Os indicadores são resumidos e não expõem informações sensíveis.','Atualize o diagnóstico antes de tomar uma decisão.'],
  profile:['Aqui você altera sua foto e seus próprios dados permitidos.','Use Sair do sistema para trocar de conta com segurança.'],
};
const allowedTopics=()=>HELP_TOPICS.filter(topic=>topic.roles.includes(S.profile?.role)&&(topic.id!=='shipping-planning'||S.profile?.is_ecommerce_manager||S.profile?.is_primary_admin));
function helpNav(){
  if(!S?.profile)return;const root=document.querySelector('.sidebar nav'),profile=root?.querySelector('[data-view="profile"]');if(!root||!profile||root.querySelector('[data-view="help"]'))return;
  const button=document.createElement('button');button.className='nav';button.dataset.view='help';button.innerHTML='<i>💡</i>Central de ajuda';button.onclick=()=>{S.view='help';renderApp()};profile.parentNode.insertBefore(button,profile);
}
function quickHelp(){
  if(!S?.profile||S.view==='help'||document.querySelector('#quickHelp'))return;const actions=document.querySelector('.page-head .head-actions');if(!actions)return;
  const button=document.createElement('button');button.id='quickHelp';button.className='outline compact-action quick-help-button';button.type='button';button.title='Abrir ajuda desta tela';button.setAttribute('aria-label','Abrir ajuda desta tela');button.innerHTML='<span class="quick-help-icon" aria-hidden="true">💡</span><span>Ajuda</span>';button.onclick=()=>openQuickHelp();actions.appendChild(button);
}
function openQuickHelp(){
  const lines=QUICK[S.view]||QUICK.home;
  document.querySelector('#modal').innerHTML=`<div class="modal"><section class="modal-box help-quick"><div class="modal-head"><div><p class="eyebrow">AJUDA RÁPIDA</p><h2>${esc(document.querySelector('.page-head h1')?.textContent||'Harmony Store')}</h2></div><button type="button" data-help-close>×</button></div><ul>${lines.map(line=>`<li>${esc(line)}</li>`).join('')}</ul><div class="form-actions"><button class="outline" type="button" data-help-close>Fechar</button><button class="primary" type="button" id="openFullHelp">Abrir manual completo</button></div></section></div>`;
  document.querySelectorAll('[data-help-close]').forEach(item=>item.onclick=()=>document.querySelector('#modal').innerHTML='');
  document.querySelector('#openFullHelp').onclick=()=>{document.querySelector('#modal').innerHTML='';S.view='help';renderApp()};
}
function renderHelp(page){
  const topics=allowedTopics();page.innerHTML=`<div class="page">${head('CENTRAL DE AJUDA','Como podemos ajudar?','Orientações práticas para usar o Harmony Store com segurança.')}<section class="help-hero card"><div><span>MANUAL HARMONY</span><h2>Encontre a resposta em poucos segundos.</h2><p>Pesquise uma tarefa ou escolha um módulo abaixo.</p></div><label><span>Buscar no manual</span><input id="helpSearch" type="search" list="helpSearchSuggestions" enterkeyhint="search" autocomplete="off" placeholder="Ex.: solicitação, produção, senha"><datalist id="helpSearchSuggestions">${topics.map(topic=>`<option value="${esc(topic.title)}"></option>`).join('')}</datalist></label></section><div class="help-grid">${topics.map(topic=>`<article class="help-topic" data-help-topic="${topic.id}" data-help-text="${esc([topic.title,topic.summary,...topic.steps].join(' '))}"><i>${topic.icon}</i><div><h3>${esc(topic.title)}</h3><p>${esc(topic.summary)}</p></div><button class="ghost" data-open-topic="${topic.id}">Ver orientação</button></article>`).join('')}</div><div class="empty" id="helpEmpty" hidden>Nenhuma orientação encontrada.</div>${S.profile.role==='admin'?`<section class="card help-admin-docs"><div><p class="eyebrow">DOCUMENTAÇÃO TÉCNICA</p><h2>Arquitetura, segurança e continuidade</h2><p>Consulte regras de negócio, permissões, backup, recuperação e histórico de versões.</p></div><div class="actions"><button class="outline" id="showChangelog">Ver novidades</button><button class="primary" id="showTechnicalMap">Mapa técnico</button></div></section>`:''}</div>`;
  document.querySelectorAll('[data-open-topic]').forEach(button=>button.onclick=()=>topicModal(topics.find(topic=>topic.id===button.dataset.openTopic)));
  const search=document.querySelector('#helpSearch'),filterHelp=()=>{const term=normalizeSearch(search.value);let visible=0;document.querySelectorAll('[data-help-topic]').forEach(card=>{card.hidden=Boolean(term&&!normalizeSearch(card.dataset.helpText).includes(term));if(!card.hidden)visible++});document.querySelector('#helpEmpty').hidden=visible>0};search.oninput=filterHelp;search.onsearch=filterHelp;search.onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();filterHelp()}};
  if(document.querySelector('#showChangelog'))document.querySelector('#showChangelog').onclick=changelogModal;
  if(document.querySelector('#showTechnicalMap'))document.querySelector('#showTechnicalMap').onclick=technicalModal;
}
function topicModal(topic){if(!topic)return;document.querySelector('#modal').innerHTML=`<div class="modal"><section class="modal-box help-detail"><div class="modal-head"><div><p class="eyebrow">${topic.icon} MANUAL</p><h2>${esc(topic.title)}</h2></div><button type="button" data-help-close>×</button></div><p>${esc(topic.summary)}</p><ol>${topic.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol><button class="primary full" type="button" data-help-close>Entendi</button></section></div>`;document.querySelectorAll('[data-help-close]').forEach(item=>item.onclick=()=>document.querySelector('#modal').innerHTML='')}
async function changelogModal(){let text='';try{text=await (await fetch('./CHANGELOG.md',{cache:'no-store'})).text()}catch{}const versions=[...text.matchAll(/^## \[([^\]]+)\][^\n]*\n([\s\S]*?)(?=^## \[|$)/gm)].slice(0,5);document.querySelector('#modal').innerHTML=`<div class="modal"><section class="modal-box help-detail"><div class="modal-head"><div><p class="eyebrow">NOVIDADES</p><h2>Histórico de versões</h2></div><button type="button" data-help-close>×</button></div>${versions.length?versions.map(item=>`<article class="changelog-version"><b>${esc(item[1])}</b><p>${esc(item[2].replace(/^### .+$/gm,'').replace(/^[-*] /gm,'• ').trim())}</p></article>`).join(''):'<p>O histórico será exibido após a próxima atualização.</p>'}<button class="primary full" type="button" data-help-close>Fechar</button></section></div>`;document.querySelectorAll('[data-help-close]').forEach(item=>item.onclick=()=>document.querySelector('#modal').innerHTML='')}
function technicalModal(){document.querySelector('#modal').innerHTML=`<div class="modal"><section class="modal-box help-detail"><div class="modal-head"><div><p class="eyebrow">MAPA TÉCNICO</p><h2>Como o sistema funciona</h2></div><button type="button" data-help-close>×</button></div><div class="technical-flow"><b>Usuária</b><span>→</span><b>Aplicativo PWA</b><span>→</span><b>Supabase protegido</b></div><ul><li>GitHub Pages publica a interface oficial.</li><li>Supabase Auth controla sessões e acessos.</li><li>RLS e RPCs aplicam permissões e transações.</li><li>Storage guarda fotos com políticas específicas.</li><li>Edge Functions executam usuários, notificações e diagnósticos seguros.</li></ul><button class="primary full" type="button" data-help-close>Fechar</button></section></div>`;document.querySelectorAll('[data-help-close]').forEach(item=>item.onclick=()=>document.querySelector('#modal').innerHTML='')}
const previousRenderPage=renderPage;renderPage=async function(){if(S.view==='help')return renderHelp(document.querySelector('#page'));return previousRenderPage()};
new MutationObserver(()=>{helpNav();quickHelp()}).observe(document.body,{childList:true,subtree:true});helpNav();quickHelp();
})();
