(()=>{
const HELP_TOPICS=[
  {id:'start',roles:['collaborator','receiver','admin'],icon:'🌷',title:'Primeiros passos',summary:'Entrar, navegar, atualizar dados e sair com segurança.',steps:['Use o menu inferior no celular ou lateral no computador.','Toque em Atualizar quando precisar buscar dados recentes.','Em Meu perfil você altera foto e senha e pode sair da conta.']},
  {id:'request',roles:['collaborator','receiver'],icon:'📝',title:'Solicitar matéria-prima',summary:'Monte uma solicitação e acompanhe somente os seus pedidos.',steps:['Abra Nova solicitação e informe a quantidade de cada material.','A lista mostra somente matérias-primas de produção; café, limpeza e outros suprimentos ficam no módulo interno.','Revise a lista e envie; a empresa definirá data e entrega ou coleta.','Enquanto estiver pendente, abra o pedido para editar ou cancelar.']},
  {id:'notifications',roles:['collaborator','receiver','admin'],icon:'🔔',title:'Notificações',summary:'Leia avisos internos e acompanhe comunicados importantes da Harmony.',steps:['O número no menu mostra quantas notificações ainda não foram lidas.','Toque no aviso para abrir os detalhes e confirmar a leitura.','O ADM principal envia avisos individuais pelo cadastro ou globais para toda a equipe.']},
  {id:'admin-requests',roles:['admin'],icon:'📋',title:'Administrar solicitações',summary:'Separar, ajustar, agendar, concluir ou cancelar pedidos.',steps:['Abra a solicitação e confira todos os itens.','Na separação, ajuste quantidades ou remova itens indisponíveis.','Agende todos os itens para o mesmo dia e finalize informando quem entregou e recebeu.','O ADM principal pode usar Editar solicitação completa para adicionar produtos ou corrigir quantidades em qualquer fase; entregas concluídas ajustam estoque e relatórios automaticamente.']},
  {id:'products',roles:['admin'],icon:'🧼',title:'Produtos e estoque',summary:'Cadastrar materiais, fotos, fornecedores e estoque com segurança.',steps:['Cadastre nome, unidade, categoria, cor, foto e limites de estoque.','Use campos personalizados quando um material precisar de informação própria.','As alterações de produto, estoque e fornecedor são salvas juntas.']},
  {id:'production',roles:['collaborator','receiver','admin'],icon:'📦',title:'Produção recebida',summary:'Conferência por caixa, modelo, cor e quantidade oficial.',steps:['Recebimento ou ADM registra vários itens dentro de uma única coleta.','Se outra caixa da mesma coleta aparecer depois, use Reabrir e editar para acrescentá-la ao registro original.','Coletas com pagamento já realizado ficam protegidas; as demais são recalculadas e registradas no histórico.']},
  {id:'production-orders',roles:['collaborator','receiver','admin'],icon:'📋',title:'Ordens de produção',summary:'Planejamento semanal por colaboradora, com fotos, cores e quantidades.',steps:['O ADM cria a ordem usando os mesmos modelos e cores do catálogo de produtos acabados.','A colaboradora recebe uma notificação, abre a lista e confirma que recebeu as orientações.','Use Gerar PDF para imprimir ou salvar a lista profissionalmente.','Este módulo não calcula pagamento; os valores continuam exclusivamente no recebimento pela contagem oficial.']},
  {id:'payments',roles:['collaborator','admin'],icon:'💗',title:'Pagamentos semanais',summary:'Acompanhar fechamentos de segunda a domingo.',steps:['O ADM fecha a semana somente depois da conferência.','A colaboradora visualiza o valor após o fechamento, em Meus pagamentos.','Correções exigem reabertura administrativa e ficam registradas.']},
  {id:'intelligence',roles:['admin'],icon:'📈',title:'Inteligência e fornecedores',summary:'Transformar consumo em previsão e pedidos de compra.',steps:['Vincule cada matéria-prima ao fornecedor preferencial.','Use filtros por período, produto e colaboradora nos relatórios.','As sugestões consideram consumo, estoque disponível, segurança e prazo.']},
  {id:'internal-supplies',roles:['admin','receiver'],icon:'🧺',title:'Suprimentos e compras internas',summary:'Solicitar itens do e-commerce e registrar compras por cupom fiscal.',steps:['Recebimento marca somente os itens que estão faltando; não precisa informar quantidade ou valor.','Este catálogo é separado das matérias-primas de produção.','O ADM pode cadastrar uma foto em cada suprimento para facilitar a identificação.','O ADM abre a solicitação, fotografa o cupom e confere a leitura antes de salvar a compra.','Compras não solicitadas entram como Compra direta, sem criar uma solicitação fictícia.','O relatório compara preço anterior e atual, diferença em reais e percentual, média, menor e maior preço.']},
  {id:'ideas',roles:['admin'],icon:'💡',title:'Ideias e Evolução',summary:'Registrar melhorias e preparar uma solicitação organizada para o Codex.',steps:['Registre título, área, prioridade, descrição e o problema que deseja resolver.','Use a imagem opcional somente quando ela ajudar a demonstrar a ideia.','Toque em Preparar para o Codex para copiar um texto com contexto, impacto, segurança, riscos e pedido de plano antes da implementação.']},
  {id:'team',roles:['admin'],icon:'👥',title:'Pessoas e acessos',summary:'Cadastrar, editar, desativar e proteger contas.',steps:['Crie login e senha temporária forte para cada pessoa.','A pessoa troca a senha no primeiro acesso.','Cadastros com histórico são desativados, nunca apagados junto com seus registros.']},
  {id:'security',roles:['collaborator','receiver','admin'],icon:'🔐',title:'Segurança da conta',summary:'Boas práticas simples para proteger o acesso.',steps:['Nunca compartilhe sua senha ou códigos de acesso.','Use Sair do sistema quando o aparelho for compartilhado.','Se notar algo diferente, avise o ADM e troque a senha.']},
  {id:'health',roles:['admin'],icon:'🩺',title:'Saúde do Sistema',summary:'Interpretar disponibilidade, backup, Storage e alertas.',steps:['Verde significa operação normal; amarelo pede acompanhamento; vermelho exige ação.','O painel mostra dados resumidos, nunca senhas ou informações pessoais.','Backup só fica verde depois de uma cópia válida e recente.']},
];
const QUICK={
  home:['Veja o resumo do dia e as solicitações mais recentes.','Os cartões mudam conforme o seu perfil e mostram somente dados permitidos.'],
  new:['Informe qualquer quantidade necessária e revise antes de enviar.','A data e a forma de entrega ou coleta serão definidas pela empresa.'],
  requests:['Abra um cartão para consultar detalhes e ações disponíveis.','Colaboradoras veem apenas os próprios pedidos; ADM vê a operação completa.','O botão Editar solicitação completa aparece somente para o ADM principal e registra o motivo de cada correção.'],
  notifications:['O contador mostra os avisos ainda não abertos.','Toque em uma notificação para confirmar a leitura e consultar o prazo.','Somente o ADM principal pode enviar avisos individuais ou globais.'],
  products:['Cadastros, estoque e fornecedor são salvos em uma única operação segura.','Use uma foto leve para facilitar a identificação no celular.','Marque Ocultar para colaboradoras de produção nos produtos exclusivos do e-commerce; ADMs e recebimento continuarão vendo o item.'],
  production:['ADM principal, ADM e Recebimento podem editar coletas abertas de toda a equipe.','Em uma semana fechada, use Reabrir e editar; a data e a colaboradora permanecem protegidas.','Depois de salvar, a contagem oficial e o total semanal são recalculados automaticamente.'],
  categories:['Categorias organizam o catálogo e podem ser desativadas sem apagar produtos.'],
  team:['Somente ADM administra acessos.','Cadastros com histórico são desativados para preservar solicitações e pagamentos.'],
  fields:['Crie somente os campos realmente necessários.','Campos inativos deixam de aparecer nos novos cadastros.'],
  audit:['Use filtros para localizar alterações por pessoa, ação ou período.','O histórico é imutável e gerado por operações confiáveis.'],
  production:['Registre vários modelos e cores dentro da mesma coleta.','Pagamento usa sempre a quantidade oficial conferida.'],
  'production-orders':['O ADM monta uma lista individual com modelo, cor, foto e quantidade.','Rascunhos ficam visíveis somente para os ADMs; ao enviar, a colaboradora recebe uma notificação.','A ordem é planejamento e nunca altera a contagem oficial ou o pagamento.'],
  intelligence:['Relatórios ajudam a prever compras e comparar consumo por período.','Vincule fornecedores aos produtos para obter sugestões completas.','Na aba Ideias e Evolução, registre propostas e use Preparar para o Codex quando quiser estudá-las.'],
  'internal-supplies':['Recebimento solicita apenas os itens que estão faltando, sem quantidade.','O catálogo interno não se mistura com a solicitação de matéria-prima.','No Catálogo, o ADM pode cadastrar, trocar ou remover a foto do suprimento.','O ADM pode anexar um cupom à solicitação ou registrar uma compra direta.','Confira todos os dados extraídos da foto antes de confirmar; o relatório registra o histórico de preços.'],
  health:['Os indicadores são resumidos e não expõem informações sensíveis.','Atualize o diagnóstico antes de tomar uma decisão.'],
  profile:['Aqui você altera sua foto e seus próprios dados permitidos.','Use Sair do sistema para trocar de conta com segurança.'],
};
const allowedTopics=()=>HELP_TOPICS.filter(topic=>topic.roles.includes(S.profile?.role));
function helpNav(){
  if(!S?.profile)return;const root=document.querySelector('.sidebar nav'),profile=root?.querySelector('[data-view="profile"]');if(!root||!profile||root.querySelector('[data-view="help"]'))return;
  const button=document.createElement('button');button.className='nav';button.dataset.view='help';button.innerHTML='<i>💡</i>Central de ajuda';button.onclick=()=>{S.view='help';renderApp()};profile.parentNode.insertBefore(button,profile);
}
function quickHelp(){
  if(!S?.profile||S.view==='help'||document.querySelector('#quickHelp'))return;const actions=document.querySelector('.page-head .head-actions');if(!actions)return;
  const button=document.createElement('button');button.id='quickHelp';button.className='outline compact-action quick-help-button';button.type='button';button.title='Abrir ajuda desta tela';button.setAttribute('aria-label','Abrir ajuda desta tela');button.innerHTML='<span class="quick-help-icon" aria-hidden="true">💡</span><span>Ajuda</span>';button.onclick=()=>openQuickHelp();actions.appendChild(button);
}
function openQuickHelp(){
  const lines=QUICK[S.view]||QUICK.home;
  document.querySelector('#modal').innerHTML=`<div class="modal"><section class="modal-box help-quick"><div class="modal-head"><div><p class="eyebrow">AJUDA RÁPIDA</p><h2>${esc(document.querySelector('.page-head h1')?.textContent||'Harmony Store')}</h2></div><button type="button" data-help-close>×</button></div><ul>${lines.map(line=>`<li>${esc(line)}</li>`).join('')}</ul><div class="form-actions"><button class="outline" type="button" data-help-close>Fechar</button><button class="primary" type="button" id="openFullHelp">Abrir manual completo</button></div></section></div>`;
  document.querySelectorAll('[data-help-close]').forEach(item=>item.onclick=()=>document.querySelector('#modal').innerHTML='');
  document.querySelector('#openFullHelp').onclick=()=>{document.querySelector('#modal').innerHTML='';S.view='help';renderApp()};
}
function renderHelp(page){
  const topics=allowedTopics();page.innerHTML=`<div class="page">${head('CENTRAL DE AJUDA','Como podemos ajudar?','Orientações práticas para usar o Harmony Store com segurança.')}<section class="help-hero card"><div><span>MANUAL HARMONY</span><h2>Encontre a resposta em poucos segundos.</h2><p>Pesquise uma tarefa ou escolha um módulo abaixo.</p></div><label><span>Buscar no manual</span><input id="helpSearch" type="search" placeholder="Ex.: solicitação, produção, senha"></label></section><div class="help-grid">${topics.map(topic=>`<article class="help-topic" data-help-topic="${topic.id}" data-help-text="${esc([topic.title,topic.summary,...topic.steps].join(' '))}"><i>${topic.icon}</i><div><h3>${esc(topic.title)}</h3><p>${esc(topic.summary)}</p></div><button class="ghost" data-open-topic="${topic.id}">Ver orientação</button></article>`).join('')}</div><div class="empty" id="helpEmpty" hidden>Nenhuma orientação encontrada.</div>${S.profile.role==='admin'?`<section class="card help-admin-docs"><div><p class="eyebrow">DOCUMENTAÇÃO TÉCNICA</p><h2>Arquitetura, segurança e continuidade</h2><p>Consulte regras de negócio, permissões, backup, recuperação e histórico de versões.</p></div><div class="actions"><button class="outline" id="showChangelog">Ver novidades</button><button class="primary" id="showTechnicalMap">Mapa técnico</button></div></section>`:''}</div>`;
  document.querySelectorAll('[data-open-topic]').forEach(button=>button.onclick=()=>topicModal(topics.find(topic=>topic.id===button.dataset.openTopic)));
  const search=document.querySelector('#helpSearch');search.oninput=()=>{const term=normalizeSearch(search.value);let visible=0;document.querySelectorAll('[data-help-topic]').forEach(card=>{card.hidden=Boolean(term&&!normalizeSearch(card.dataset.helpText).includes(term));if(!card.hidden)visible++});document.querySelector('#helpEmpty').hidden=visible>0};
  if(document.querySelector('#showChangelog'))document.querySelector('#showChangelog').onclick=changelogModal;
  if(document.querySelector('#showTechnicalMap'))document.querySelector('#showTechnicalMap').onclick=technicalModal;
}
function topicModal(topic){if(!topic)return;document.querySelector('#modal').innerHTML=`<div class="modal"><section class="modal-box help-detail"><div class="modal-head"><div><p class="eyebrow">${topic.icon} MANUAL</p><h2>${esc(topic.title)}</h2></div><button type="button" data-help-close>×</button></div><p>${esc(topic.summary)}</p><ol>${topic.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol><button class="primary full" type="button" data-help-close>Entendi</button></section></div>`;document.querySelectorAll('[data-help-close]').forEach(item=>item.onclick=()=>document.querySelector('#modal').innerHTML='')}
async function changelogModal(){let text='';try{text=await (await fetch('./CHANGELOG.md',{cache:'no-store'})).text()}catch{}const versions=[...text.matchAll(/^## \[([^\]]+)\][^\n]*\n([\s\S]*?)(?=^## \[|$)/gm)].slice(0,5);document.querySelector('#modal').innerHTML=`<div class="modal"><section class="modal-box help-detail"><div class="modal-head"><div><p class="eyebrow">NOVIDADES</p><h2>Histórico de versões</h2></div><button type="button" data-help-close>×</button></div>${versions.length?versions.map(item=>`<article class="changelog-version"><b>${esc(item[1])}</b><p>${esc(item[2].replace(/^### .+$/gm,'').replace(/^[-*] /gm,'• ').trim())}</p></article>`).join(''):'<p>O histórico será exibido após a próxima atualização.</p>'}<button class="primary full" type="button" data-help-close>Fechar</button></section></div>`;document.querySelectorAll('[data-help-close]').forEach(item=>item.onclick=()=>document.querySelector('#modal').innerHTML='')}
function technicalModal(){document.querySelector('#modal').innerHTML=`<div class="modal"><section class="modal-box help-detail"><div class="modal-head"><div><p class="eyebrow">MAPA TÉCNICO</p><h2>Como o sistema funciona</h2></div><button type="button" data-help-close>×</button></div><div class="technical-flow"><b>Usuária</b><span>→</span><b>Aplicativo PWA</b><span>→</span><b>Supabase protegido</b></div><ul><li>GitHub Pages publica a interface oficial.</li><li>Supabase Auth controla sessões e acessos.</li><li>RLS e RPCs aplicam permissões e transações.</li><li>Storage guarda fotos com políticas específicas.</li><li>Edge Functions executam usuários, notificações e diagnósticos seguros.</li></ul><button class="primary full" type="button" data-help-close>Fechar</button></section></div>`;document.querySelectorAll('[data-help-close]').forEach(item=>item.onclick=()=>document.querySelector('#modal').innerHTML='')}
const previousRenderPage=renderPage;renderPage=async function(){if(S.view==='help')return renderHelp(document.querySelector('#page'));return previousRenderPage()};
new MutationObserver(()=>{helpNav();quickHelp()}).observe(document.body,{childList:true,subtree:true});helpNav();quickHelp();
})();
