(()=>{
const statusLabel={green:'Operando',yellow:'Atenção',red:'Indisponível',gray:'Sem dados'};
async function healthEdge(){await ensureSession();let call=()=>fetch(API+'/functions/v1/system-health',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+S.session.access_token,'Content-Type':'application/json'},body:'{}'}),response=await call();if(response.status===401){await refreshSession();response=await call()}return json(response)}
function healthNav(){if(S?.profile?.role!=='admin')return;const root=document.querySelector('.sidebar nav'),audit=root?.querySelector('[data-view="audit"]');if(!root||!audit||root.querySelector('[data-view="health"]'))return;const button=document.createElement('button');button.className='nav';button.dataset.view='health';button.innerHTML='<i>🩺</i>Saúde do Sistema';button.onclick=()=>{S.view='health';renderApp()};audit.parentNode.insertBefore(button,audit.nextSibling)}
async function renderHealth(page){page.innerHTML=`<div class="page">${head('ADMINISTRAÇÃO','Saúde do Sistema','Diagnóstico seguro e resumido da operação.','<button class="primary" id="refreshHealth">↻ Atualizar diagnóstico</button>')}<section class="health-loading card">Verificando aplicação, banco, arquivos, notificações e backups…</section></div>`;document.querySelector('#refreshHealth').onclick=()=>renderHealth(page);try{const result=await healthEdge(),items=result.items||[];page.innerHTML=`<div class="page">${head('ADMINISTRAÇÃO','Saúde do Sistema','Última verificação: '+fmt(result.checked_at),'<button class="primary" id="refreshHealth">↻ Atualizar diagnóstico</button>')}<div class="health-summary ${esc(result.overall||'gray')}"><i></i><div><small>ESTADO GERAL</small><h2>${esc(statusLabel[result.overall]||'Sem dados')}</h2><p>${esc(result.message||'Diagnóstico concluído.')}</p></div></div><div class="health-grid">${items.map(item=>`<article class="health-card ${esc(item.status||'gray')}"><header><i></i><span>${esc(item.label)}</span><b>${esc(statusLabel[item.status]||'Sem dados')}</b></header><strong>${esc(item.value||'—')}</strong><p>${esc(item.detail||'')}</p>${item.checked_at?`<small>${fmt(item.checked_at)}</small>`:''}</article>`).join('')}</div><section class="card health-guidance"><h2>Como interpretar</h2><div><span class="green">Verde</span><p>Operação normal, nenhuma ação necessária.</p><span class="yellow">Amarelo</span><p>Acompanhar e corrigir antes de afetar a rotina.</p><span class="red">Vermelho</span><p>Ação administrativa necessária.</p></div></section></div>`;document.querySelector('#refreshHealth').onclick=()=>renderHealth(page)}catch(error){page.innerHTML=`<div class="page">${head('ADMINISTRAÇÃO','Saúde do Sistema','Não foi possível concluir o diagnóstico.','<button class="primary" id="refreshHealth">Tentar novamente</button>')}<div class="health-summary red"><i></i><div><small>DIAGNÓSTICO</small><h2>Verificação indisponível</h2><p>${esc(error.message)}</p></div></div></div>`;document.querySelector('#refreshHealth').onclick=()=>renderHealth(page)}}
const beforeHealthRender=renderPage;renderPage=async function(){if(S.view==='health'&&S.profile?.role==='admin')return renderHealth(document.querySelector('#page'));return beforeHealthRender()};
let errorSent=false;async function report(code){if(errorSent||!S?.profile)return;errorSent=true;try{await rpc('record_client_error',{p_code:String(code).slice(0,80),p_context:{view:S.view,version:'v25.29'}})}catch{}finally{setTimeout(()=>errorSent=false,60000)}}
window.addEventListener('error',()=>report('client_error'));window.addEventListener('unhandledrejection',()=>report('unhandled_rejection'));
new MutationObserver(healthNav).observe(document.body,{childList:true,subtree:true});healthNav();
})();

